### ISSUE TITLE
vendored package breaks public API

### ISSUE THREAD

**Issue by GeertJohan** [grpc-ecosystem/go-grpc-middleware#105]
It looks like `google.golang.org/grpc/metadata` is now being vendored by this project. This breaks the public API of this package, which might not be your intention?

I don't believe `google.golang.org/grpc/metadata` needs to be vendored by this package. It kinda breaks type compatibility between this package and other packages using `metadata`.

```
somefile.go:74:46: cannot use stream (type "google.golang.org/grpc".ServerStream) as type "github.com/grpc-ecosystem/go-grpc-middleware/vendor/google.golang.org/grpc".ServerStream in argument to grpc_middleware.WrapServerStream:
        "google.golang.org/grpc".ServerStream does not implement "github.com/grpc-ecosystem/go-grpc-middleware/vendor/google.golang.org/grpc".ServerStream (wrong type for SendHeader method)
                have SendHeader("google.golang.org/grpc/metadata".MD) error
                want SendHeader("github.com/grpc-ecosystem/go-grpc-middleware/vendor/google.golang.org/grpc/metadata".MD) error
```

**Comment by loderunner** [comment]
I have the same issue with interceptors. It is now impossible to mix-and-match `grpc_middleware` interceptors with `grpc` interceptors.

```
server/serve.go:143:37: cannot use i (type "google.golang.org/grpc".UnaryServerInterceptor) as type "github.com/grpc-ecosystem/go-grpc-middleware/vendor/google.golang.org/grpc".UnaryServerInterceptor in argument to grpc_middleware.ChainUnaryServer
server/serve.go:143:37: cannot use grpc_middleware.ChainUnaryServer(i) (type "github.com/grpc-ecosystem/go-grpc-middleware/vendor/google.golang.org/grpc".UnaryServerInterceptor) as type "google.golang.org/grpc".UnaryServerInterceptor in argument to "google.golang.org/grpc".UnaryInterceptor
```

**Comment by Kilmar** [comment]
Same problem here but with Context

```
have Context() ".../vendor/golang.org/x/net/context".Context
want Context() ".../vendor/github.com/grpc-ecosystem/go-grpc-middleware/vendor/golang.org/x/net/context".Context
```

**Comment by chadnickbok** [comment]
Oh lawdy please remove these vendored packages. Checking in a lockfile is one thing, but checking in the entire vendor directory is Not The Way.

**Comment by GeertJohan** [comment]
@domgreen could you please look into this?

**Comment by GeertJohan** [comment]
Preferably the master branch is rolled back to 2e3f98dd05d100fd45ec7cec74cc1e48b28a92a2. Afterwards re-apply the commits added since #101 which are: b5293e3051a50fc5b3eac1eeb8383ff5b1256aff and 952ab2f8654d37d739b03d1a4e30e2c4bfa4bb18. This cleans up the ~1.8 milion changes introduced in ab28732001b56cf34568770c6309655f2388e94e.

**Comment by domgreen** [comment]
@GeertJohan will be looking at this this morning

**Comment by yifanzz** [comment]
Merged @domgreen's fix. Let us know if this fixes your issue. @GeertJohan

**Comment by GeertJohan** [comment]
Looks like the problem has been solved indeed.
Thanks @domgreen @yifanzz
