### ISSUE TITLE
Downstream interceptors are not re-executed on retry

### ISSUE THREAD

**Issue by marcwilson-g** [grpc-ecosystem/go-grpc-middleware#110]
Any interceptors chained after the retry interceptor are not re-executed in subsequent retry attempts.
For example if we have:
```
grpc_middleware.ChainUnaryClient(
  grpc_retry.UnaryClientInterceptor()
  grpc_prometheus.UnaryClientInterceptor)
```
and want the grpc_prometheus interceptor to see and time each retry independently then currently it will intercept only the first attempt.

(This was possibly a regression in 5d4723c)

I have a pull request, with tests, in:
https://github.com/grpc-ecosystem/go-grpc-middleware/pull/100

**Comment by alcore** [comment]
That would be a _mea culpa_ on my part, for assuming a chain would always execute in the order it's given.

**Comment by MatthewDolan** [comment]
Can this issue be closed now that the PR has been merged?
