### ISSUE TITLE
Adding JSON to jsonPayload with grpc_ctxtags

### ISSUE THREAD

**Issue by snktagarwal** [grpc-ecosystem/go-grpc-middleware#119]
I am trying to add json object as part of my grpc_ctxtags (which show up as jsonPayload in stackdriver). I am shoving the proto object as is, and is being converted to a "string" instead of a json object. For more visuals see this:

 jsonPayload: {
  caller:  "zap/server_interceptors.go:66"   
  conf:  "encoding:LINEAR16 sample_rate_hertz:44100 header:"RIFF\277\377\377\377WAVEfmt \020\000\000\000\001\000\001\000D\254\000\000\210X\001\000\002\000\020\000data\233\377\377\377" language_code:"en-US" session_id:"102k0KxT9EISz-G1IVynLmIUg" session_owner_id:"24f80fa2-2a82-4e7b-a1e1-ab3c2b2dcfd9" stream_start_time:<seconds:1513280382 nanos:649000000 > context:<view:SCHEDULE > "
....

I want the conf object to be a json instead of a raw string. What is the advice on this?

**Comment by mwitkow** [comment]
That looks incredibly expensive. So maybe the advice is: don't do it?

Passing massive structs around wasn't the primary usage of `grpc_ctxtags`. Consider extracting what you think is really important (e.g. `session_id`?) and pass that in through a custom interceptor.
