### ISSUE TITLE
could you clean merged branch?

### ISSUE THREAD

**Issue by zhexuany** [grpc-ecosystem/go-grpc-middleware#124]
Hello there, 

Recently, I am working on migrating from glide to dep in our project. Our project depends on this but when dep try to solve dependencies it iterates a lot branch that this project has. After I checked, a lot of them are already merged into master which means they are useless and can be removed from branch. I am wiring this to notify you guys and wish you can remove unused branches. 
Thanks in advance.

**Comment by mwitkow** [comment]
Thanks for pointing out, didn't know it was a problem.

Removed a tonne of my branches that I started the project with :)
