### ISSUE TITLE
Use protobuf v1.0.0 instead of master

### ISSUE THREAD

**Issue by warmans** [grpc-ecosystem/go-grpc-middleware#126]
Since about 2 weeks ago there is a tagged release for golang/protobuf. It would probably make sense to use this as the constraint in the Gopkg file instead of master.

https://github.com/golang/protobuf/releases

**Comment by mwitkow** [comment]
Yeah, I don't know what their policy is. Hopefully with `vgo` being more mainstream all this craziness will go away.

**Comment by srenatus** [comment]
It would be very nice to fix this -- especially with other projects having that constraint, you can quickly run into
```
Solving failure: No versions of github.com/grpc-ecosystem/go-grpc-middleware met constraints:
        master: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@master, as it has a dependency on github.com/golang/protobuf with constraint master, which has no overlap with the following existing constraints:
        ^1.0.0 from (root)
        ^1.0.0 from github.com/lyft/protoc-gen-validate@master

        master: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@master, as it has a dependency on github.com/golang/protobuf with constraint master, which has no overlap with the following existing constraints:
        ^1.0.0 from (root)
        ^1.0.0 from github.com/lyft/protoc-gen-validate@master
```

**Comment by domgreen** [comment]
@mwitkow ive actually been thinking of removing dep and dependancy management from the project ... is an ongoing discussion im having offline with @bplokta about wether we should even include this for libraries / packages 😄

**Comment by Bplotka** [comment]
Yea, I am not fan of non-std deps for library, but we have lots of it that are unavoidable, so maybe using dep mngt is actually must-have to ensure users see with what deps we tested against. 

First of all before changing anything? Can we do some releases?

**Comment by Bplotka** [comment]
@srenatus, since protobuf 1.0.0 did not change any API we use vs our used version, have you try to use https://golang.github.io/dep/docs/Gopkg.toml.html#override in your Gopkg.toml for protobuf?

**Comment by srenatus** [comment]
@Bplotka Thank you. That's another option indeed. 👍

**Comment by Tommy-42** [comment]
Hello there,

since https://github.com/grpc-ecosystem/go-grpc-middleware/issues/40 is now closed and we have a tagged release, can we match the version in `Gopkg.toml` ? or you are still discussing about removing dep :D ?

**Comment by bwplotka** [comment]
So what I was thinking... would removal of dep and moving to Go modules would help ?

**Comment by veqryn** [comment]
Switching to `^1.0.0` would probably be easier for now, but its totally up to you all.  I'm not using modules yet (waiting on that to be finalized), so whatever doesn't make `dep` complain/fail works for me.

**Comment by bobheadxi** [comment]
Switching to ^1.0.0 or anything that supports using a constraint on 1.2.0 would be really helpful - I'm having trouble introducing this dependency as well

**Comment by javasgl** [comment]
```master: Could not introduce github.com/grpc-ecosystem/grpc-gateway@master, as it has a dependency on github.com/golang/protobuf with constraint aa810b61a9c79d51363740d207bb46cf8e620ed5, which has no overlap with existing constraint master from github.com/grpc-ecosystem/go-grpc-middleware@master```

**Comment by fi0** [comment]
@bwplotka there're still many projects that use dep.
It would be nice to support both dep and go modules.

**Comment by bwplotka** [comment]
I am not sure if dep is still relevant 4 years later, so closing.
