### ISSUE TITLE
Support grpc_glog ?

### ISSUE THREAD

**Issue by tamalsaha** [grpc-ecosystem/go-grpc-middleware#127]
Does it sound reasonable to support a logging implementation using glog ? We currently use glog and would like to use that for grpc logger.

**Comment by domgreen** [comment]
Submit a PR I'm sure the team will take a look 👍

**Comment by tamalsaha** [comment]
Thanks @domgreen . I have filed #129 for this.

**Comment by mwitkow** [comment]
I assume you're talking about `grpcloggerv2` from the `grpc-go` repo?

**Comment by tamalsaha** [comment]
I used grpcloggerv2 interface so that I can write tests for it.

**Comment by bwplotka** [comment]
Let us know if this still needed - it's quite an old issue (: Also see v2 if you want to contribute this.
