### ISSUE TITLE
grpc.request.deadline and grpc.start_time precision is in seconds

### ISSUE THREAD

**Issue by matiasanaya** [grpc-ecosystem/go-grpc-middleware#131]
`grpc.request.deadline` and `grpc.start_time` use `d.Format(time.RFC3339)` which means maximum precision is in seconds. I believe it would be useful to use `d.Format(time.RFC3339Nano)` at least.

Best would be a configuration option for me to format all logged timestamps as desired.

I can work on a PR for this change if it makes sense.

**Comment by mwitkow** [comment]
@domgreen you made tracking of the elapsed time, right? It's probably best for you to take this.

**Comment by stanhu** [comment]
Can someone review https://github.com/grpc-ecosystem/go-grpc-middleware/pull/398?
