### ISSUE TITLE
Rate Limit Interceptor 

### ISSUE THREAD

**Issue by fifthaxe** [grpc-ecosystem/go-grpc-middleware#134]
Hi,

What guys do you think of a new server incerceptor thay would stall API calls for a given duration in order to prevent DoS / bruteforce.

Use case : delay every API call by 200 ms to prevent API DoS.

I know this can be done easily using an auth interceptor with a custom sleep-based function but it doesn't sound very good because it has nothing to do with auth.

**Comment by domgreen** [comment]
Hey @fifthaxe ,

Thanks for the suggestion, some protection from a problem clients is a great idea.

Having a `RateLimit` interceptor would be a better idea however the implementation would not want to sleep the incoming calls on the server we would just want to reject the calls if a user has hit the rate limit.
Thinking along the lines that if a client made n requests in a time window (both configurable) we would start to do the equivalent of `HTTP 429`.
Please feel free to put out a Work In Progress PR for this and we can talk through the implementation when we have something more.

Dom

**Comment by fifthaxe** [comment]
Sounds like we need a dummy net pipe restriction like features, that would be a great gRPC enhancement (QoS, filtering, rate limiting, latency control ...).

**Comment by domgreen** [comment]
This looks to be a good library that would be useful for doing this https://github.com/juju/ratelimit

**Comment by vtolstov** [comment]
any steps to get such interceptor?

**Comment by domgreen** [comment]
Have not seen any PRs from @fifthaxe so @vtolstov feel free to pick up 😄

**Comment by fengzixu** [comment]
I would like to take that. Can you assign this issue to me? @domgreen @mwitkow

**Comment by domgreen** [comment]
Amazing @fengzixu thats great to hear 👍 I can't currently assign you but put a PR out and we will link it here.

**Comment by vtolstov** [comment]
@fengzixu do you have time to create pr?

**Comment by fengzixu** [comment]
@vtolstov Yep. I have written some codes about this issue. I will probably submit a PR in this week(Wednesday or Thursday).
