### ISSUE TITLE
grpc_logging payloads embedded in the classic log output

### ISSUE THREAD

**Issue by jhayotte** [grpc-ecosystem/go-grpc-middleware#135]
Hi,

I am using most of go-grpc-middleware and I have a question regarding logs. I wish to **include the payload in the standard output** or **have a way to correlate both** of them.

In order to get, ideally, this king of output:
```json
{
    "level": "info",									
    "msg": "finished unary call",						
    "grpc.code": "OK",								
    "grpc.method": "Ping",							
    "grpc.service": "mwitkow.testproto.TestService", 
    "grpc.start_time": "2006-01-02T15:04:05Z07:00", 
    "grpc.request.deadline": "2006-01-02T15:04:05Z07:00",
    "grpc.request.value": "something",
    "grpc.time_ms": 1.345,		
    "peer.address": {
        "IP": "127.0.0.1",			
        "Port": 60216,				
        "Zone": ""				
    },
    "span.kind": "server",			
    "system": "grpc"				
    "grpc.request.content": {		        
        "msg" : {														
            "value": "something",											
            "sleepTimeMs": 9999											
        }
    },
    "custom_field": "custom_value",					
    "custom_tags.int": 1337,							
    "custom_tags.string": "something",				
}
```
Below, an extract of my interceptor. 
```golang
	grpc_zap.UnaryServerInterceptor(logger.Zap, opts...),
	grpc_zap.PayloadUnaryServerInterceptor(logger.Zap, alwaysLoggingDeciderServer),	
```

One simple way could be to pass a GUID in the context and flag both logs with it. Then we could aggregate both results in Grafana. It' not optimal but would work, though.  🤔 

By the way, thanks for the amazing work!

**Comment by mwitkow** [comment]
So the reason why the payload is separate is to facilitate streaming requests: one log entry per emitted payload. This way you can flash statements as they come.

As for tagging, that's already supported. Both interceptors should be automatically adding whatever you're getting from [`grpc_ctxtags`](https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/tags) to every log statement made. 

We are using it together with [`grpc_opentracing`](https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/tracing/opentracing) to get a request trace/span number automatically tagged. 

Does this help?

**Comment by jhayotte** [comment]
Thank you @mwitkow for the explanation. I close this issue.
