### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by maguro** [grpc-ecosystem/go-grpc-middleware#145]
Having CORS support for golang gRPC would be nice and it seems to be technically possible, although one must craft a solution by hand.  Having a simple pluggable framework would ease the pain/drudgery and also serve as a guide to new gRPC developers.

It’s not exactly a middleware thing like the interceptors in this project, but this project struck me as the goto project for tasks of this ilk.

 I’m happy to submit a PR or donate a project. Thoughts?

**Comment by bwplotka** [comment]
Sounds like irrelevant as it is project for interceptors 🤔  Thanks anyway, we can reopen if you still need this and you think this repo is a good fit.
