### ISSUE TITLE
Can I start auth proxy?

### ISSUE THREAD

**Issue by arturgspb** [grpc-ecosystem/go-grpc-middleware#158]
I have python and java grpc microservice.

Need start grcp proxy server with JWT authenticate as facade proxy server.
For example in the end I need this schema:

1) Client -- GRPC (not REST) request with JWT in Header --> 

2) ProxyFacade (decoding JWT and add to Context UserID and scopes) --- Request Python or Java backend ---> 

3) Python Backed (read UserID and working without JWT decoding)

How I can do it?

**Comment by arturgspb** [comment]
Ref: https://github.com/grpc/grpc-go/issues/2261

**Comment by domgreen** [comment]
Hey @arturgspb have you had a look at the [auth middleware](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/auth/auth.go)? 
You should be able to get the header from the context and write a validation func for it.

**Comment by arturgspb** [comment]
@domgreen hi! I wrote that I want to do this in a separate service.
For example - Google Cloud Endpoints.

**Comment by domgreen** [comment]
I am not sure on your setup but I think you could probably just create a simple proxy service that takes the request, uses the middleware above, then forwards on the request to the intended service.

**Comment by arturgspb** [comment]
I would like the proxy service not to know what specifically it will proxy. So she just checked the Headers and that's it. Those. it should not use the generated code from proto files.

**Comment by vadimi** [comment]
@arturgspb take a look at https://github.com/mwitkow/grpc-proxy. It will give you an idea how to create a generic grpc proxy that does not require any knowledge of your specific message types.

**Comment by arturgspb** [comment]
Thx a lot! I decided my question.

https://github.com/grpc/grpc-go/issues/2261#issuecomment-416507608
