### ISSUE TITLE
grpc_ctxtags allow for conditional tagging

### ISSUE THREAD

**Issue by jordancoblin** [grpc-ecosystem/go-grpc-middleware#167]
Currently, it is possible to conditionally log tags using the `WithDecider` function in `grpc_logrus`. However, this does not allow the flexibility to choose _which_ tags to log, it's either all or none. For example, given tags `a, b, c`, I may want to log tags `a` and `b` in one case, and tag `c` in another case.

One way to solve this would be to allow for conditional tagging - possibly an equivalent `WithDecider` function, except for adding tags.

**Comment by bwplotka** [comment]
Selector now exists to support this case https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.3/interceptors/selector
