### ISSUE TITLE
FR: In auth package, add exclude path to Interceptor builder

### ISSUE THREAD

**Issue by hxzhao527** [grpc-ecosystem/go-grpc-middleware#176]
**The real situation:**
I want to use [grpc-go/health](https://github.com/grpc/grpc-go/tree/master/health) which fellows the standard [gRPC health checking protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md). And then it will work with [consul](https://www.consul.io/api/agent/check.html#grpc) properly.

Actually, we have some methods or services which don't require `auth` in a grpc-server, like `health`.
For these method or services, we can use `ServiceAuthFuncOverride` to just `pass`. But no authentication required is different from `pass`.

**solution**
So we need a way to exclude those methods/svc.we can change the `Interceptor` builder.
```golang
func UnaryServerInterceptor(authFunc AuthFunc, excludePattern ...string) grpc.UnaryServerInterceptor{
...
}
func StreamServerInterceptor(authFunc AuthFunc, excludePattern ...string) grpc.StreamServerInterceptor {}
```

This can work with the existing code well.

**Comment by srenatus** [comment]
For what it's worth, the `auth` helpers are _so simplistic_, you could also implement the `{Unary,Stream}ServerInterceptor` yourself; basically inlining the helper method code... 🤔

**Comment by nlamirault** [comment]
@hxzhao527 you could also use this: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/auth/auth.go#L25

**Comment by hxzhao527** [comment]
@srenatus  Haha, :smile: , I did just implement the` {Unary,Stream}ServerInterceptor` by myself.
But I think this is `middleware`'s work.

@nlamirault Thanks. We can attach a `AuthFuncOverride` to `grpc-go/health`, but not directly. Indeed, we have many way to make a service accept anonymous. I would like a `middleware` way.
