### ISSUE TITLE
make rpc_ctxtags.SetInContext  public access

### ISSUE THREAD

**Issue by micanzhang** [grpc-ecosystem/go-grpc-middleware#182]
for some reason, we want to copy `rpc_ctxtags.Tags` from one to another `context.Context`, and looks like it private function to do it,  is it  possible to make this method public?

**Comment by mkorolyov** [comment]
Any comments? I would contribute if it is acceptable

**Comment by johanbrandhorst** [comment]
As an alternative to changing the public API of this package, which may have unintended consequences, have you considered writing a wrapping context that allows you to copy values from one to another? Presumably you don't just want to copy tags, but you probably want to decouple the lifetime. Something like this allows you to keep all the values of an existing context and just remove the deadline/cancellation:

```go
type asyncCtx struct {
	context.Context
}

func (a asyncCtx) Done() <-chan struct{} {
	return make(chan struct{})
}

func (a asyncCtx) Deadline() (time.Time, bool) {
	return time.Time{}, false
}

func (a asyncCtx) Err() error {
	return nil
}
```

Use it like this:
```go
go func() {
    callFunctionWithSeparateLifetime(asyncCtx{ctx}, var1, var2)
}()
```

**Comment by mkorolyov** [comment]
Let’s say I have grpc gateway which has graphql endpoint, I want to fill context tags in graphql resolver so all chained grpc middlewares will use filled tags. That’s why i need a way to init tags

**Comment by johanbrandhorst** [comment]
Ah, so you want a graphql "interceptor"? That's a different use case. I can see how exposing the API would be useful for that, but couldn't we just make a more useful function? What kind of structure would you need to be able to use the interceptor in graphql?

**Comment by mkorolyov** [comment]
Sorry, I wan't clear enough. 
We have Grpc gateway with bunch of http middlewares, some of them enriching the context. Also we have Grpc framework as base for tens of Microservices. What I want is to have common approach dealing with context and meta data read/write both in gateway and grpc microservices. So I need a way to populate context with meta from http middlewares, and reuse approach in populating context in Grpc middlewares. There is already a way to do it with help of http headers, but it forces us to implement same problem twice.

**Comment by johanbrandhorst** [comment]
Hm, would a client side interceptor help? So you could use it in the gRPC gateway dial. Sorry if it seems like I'm avoiding the issue but there is a real, hard to predict cost to opening up extra API.

**Comment by mkorolyov** [comment]
We already have client interceptor which is used in dial chain, and that client interceptor used both in gateway and common ms, which extracts tags from context and fills out coming GRPC metadata.
I see your concerns but actually can't imagine right any side effects from make this part of API public.
