### ISSUE TITLE
go modules support

### ISSUE THREAD

**Issue by lopezator** [grpc-ecosystem/go-grpc-middleware#185]
Add support for GO modules.

As the current https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/.travis.yml supports go 1.8.x does this feels enough to launch a new major release?

Maybe v1.1.0?

CC/ @domgreen @mwitkow

**Comment by mrxliu** [comment]
verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/go.mod: checksum mismatch
	downloaded: h1:FiyG127CGDf3tlThmgyCl78X/SZQqEOJBCDaAfeWzPs=
	go.sum:     h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=

**Comment by yankooo** [comment]
I can't use go module to sync import "github.com/grpc-ecosystem/go-grpc-middleware/ratelimit", Is it because the ratelimitpackage was updated yesterday?

**Comment by domgreen** [comment]
Have moved from dep to go mod ... @mrxliu @yankooo does this help with your issue?

Closing this Issue if not fixed lets raise a new one for specific problems that are being noticed.
