### ISSUE TITLE
Checksum Mismatch on go get

### ISSUE THREAD

**Issue by bpicolo** [grpc-ecosystem/go-grpc-middleware#193]
Getting some surprising behavior on occasion from go installs

```bash
go: verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0: checksum mismatch
	downloaded: h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
	go.sum:     h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=
```

This is inconsistent behavior, but it's only occurring for go-grpc-middleware. Is it possible github has a bad cache entry for this tag? Unsure what could cause this behavior

**Comment by coadler** [comment]
This is due to a breaking change in checksum generation between Go  `1.11.3` ~> `1.11.4`.
See: https://github.com/golang/go/issues/29278

You should be able to just remove the go-grpc-middleware entries from your `go.sum` and `go get github.com/grpc-ecosystem/go-grpc-middleware` again.

**Comment by bpicolo** [comment]
@coadler  Thanks! I guess the issue must be that some of my CI hosts are getting a distinct docker container patch version.

**Comment by dylan-bourque** [comment]
I saw this same error (with the same mismatched checksums) today after upgrading from Go 1.12.1 to 1.12.4.  FWIW, removing the `.../go-grpc-middleware...` lines from `go.sum` and re-downloading the module also fixed the issue for me.
```
> go version
go version go1.12.4 linux/amd64

> go get github.com/grpc-ecosystem/go-grpc-middleware
go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.0.0
verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0: checksum mismatch
        downloaded: h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
        go.sum:     h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=
```

**Comment by dylan-bourque** [comment]
Relevant additional point, it's definitely possible that the original reference in my `go.sum` was generated using Go 1.11.

**Comment by thepudds** [comment]
My guess would be an old entry in the `go.sum` left over from 1.11.3 or earlier?

FWIW, a quick test did not reproduce this. I get these checksums computed from scratch:

```
go1.11.3
github.com/grpc-ecosystem/go-grpc-middleware v1.0.0 h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=

go1.11.4
github.com/grpc-ecosystem/go-grpc-middleware v1.0.0 h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=

go1.12.1
github.com/grpc-ecosystem/go-grpc-middleware v1.0.0 h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=

go1.12.4
github.com/grpc-ecosystem/go-grpc-middleware v1.0.0 h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
```

The test:
```cd $(mktemp -d)
go mod init tempmod
echo "package tempmod" > tempmod.go
export GOPATH=$(mktemp -d)

for GO in go1.11.3 go1.11.4 go1.12.1 go1.12.4; do
    rm -f go.sum
    echo $GO
    $GO clean -modcache
    $GO get github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0 &> /dev/null
    grep 'go-grpc-middleware v1.0.0 h1' go.sum                
    echo
done
```
