### ISSUE TITLE
Question about package naming

### ISSUE THREAD

**Issue by ghouscht** [grpc-ecosystem/go-grpc-middleware#197]
Hi,
I was working on a PR for [jaegertracing](https://github.com/jaegertracing/jaeger) where this library is also used. I had some trouble because of the naming conventions that were used for this library.  

For example the jaeger imports `github.com/grpc-ecosystem/go-grpc-middleware/retry` the actual package name for this import however is `grpc_retry`. I think this is not ideal, because most of the standard tooling doesn't handle this very well (at least I think). 
For example, my (I would call this standard) vim-go configuration removes/adds unused/used imports automatically and the `github.com/grpc-ecosystem/go-grpc-middleware/retry` import was always removed, because its referenced under a different name (grpc_retry not retry) which let's the IDE think its not needed.

There is also an [article](https://blog.golang.org/package-names) on the golang blog which summaraizes package naming very well. Have a look at sections `Package names` and `Package paths` which state:

> A Go package has both a name and a path. The package name is specified in the package statement of its source files; client code uses it as the prefix for the package's exported names. Client code uses the package path when importing the package. By convention, the last element of the package path is the package name:

So I was wondering what's the reason why this "convention" isn't respected by your library?
Thanks - Thomas

**Comment by domgreen** [comment]
I agree the naming is currently bad in this repo ... as we go along and update packages we should look to update these. Will have to be extra careful when updating package names due to any external usages.

If there was a nice pattern or way to upgrade these and keep backwards compatibility that would be ideal.

The second idea would be that we fix all of these when we do a major version bump.

**Comment by domgreen** [comment]
Thinking about when we did some of the ctx changes we renamed packages a whole lot ... we could incrementally fix this by creating the new packages and basically keeping the old cruft as very shallow packages that just point to the new package.

**Comment by ghouscht** [comment]
Good to hear, that you're willing to "fix" this in the future. Just ping me if you need help!
