### ISSUE TITLE
v1.0.0/go.mod: checksum mismatch

### ISSUE THREAD

**Issue by mrxliu** [grpc-ecosystem/go-grpc-middleware#206]
verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0/go.mod: checksum mismatch
	downloaded: h1:FiyG127CGDf3tlThmgyCl78X/SZQqEOJBCDaAfeWzPs=
	go.sum:     h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
go

**Comment by simonrad** [comment]
I got similar errors, quite strange.

```
verifying github.com/grpc-ecosystem/go-grpc-middleware@v0.0.0-20180522105215-e9c5d9645c43: checksum mismatch
    downloaded: h1:WF3hEPHuOkYZ8ciYf67rN96IoyTvYJaqA7RSVrsm0/s=
    go.sum:     h1:PPXATDiQACyWP4+6Wyvl+8v5bH/xYzDJMfPhse5/b14=
```

**Comment by alexcusack** [comment]
I've run into this error as well, same checksum diff others are seeing

**Comment by mylxsw** [comment]
Got same errors

	go: downloading google.golang.org/grpc v1.17.0
	go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.0.0
	go: downloading github.com/vadv/gopher-lua-libs v0.0.0-20190324071824-ee99d7e6a804
	go: downloading gopkg.in/yaml.v2 v2.2.2
	go: downloading github.com/yuin/gopher-lua v0.0.0-20190206043414-8bfc7677f583
	verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0: checksum mismatch
		downloaded: h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
		go.sum:     h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=

**Comment by mantree** [comment]
Seeing the same when revendoring:

verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0: checksum mismatch
	downloaded: h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
	go.sum:     h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=

**Comment by mantree** [comment]
Adding the following to go.mod replace section gets things moving:

	github.com/grpc-ecosystem/go-grpc-middleware => github.com/grpc-ecosystem/go-grpc-middleware v1.0.0+incompatible

**Comment by glenfordwilliams** [comment]
getting this as well 
```
verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0: checksum mismatch
	downloaded: h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
	go.sum:     h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=
```

**Comment by domgreen** [comment]
Now we have moved to `go mod` is this still an issue or has the move fixed the issue?

**Comment by stanislavprokopov** [comment]
i still have this error, +incompatible does not help, looks like its related to https://github.com/golang/go/issues/29278
