### ISSUE TITLE
Race in metautils

### ISSUE THREAD

**Issue by viru** [grpc-ecosystem/go-grpc-middleware#21]
I'm not sure if I use your library correctly, but I'm getting race with this code:
```
package main

import (
	"context"

	"github.com/mwitkow/go-grpc-middleware/util/metautils"
	"google.golang.org/grpc/metadata"
)

func main() {
	md := metadata.Pairs("key", "value")
	parent := metadata.NewContext(context.Background(), md)
	for i := 0; i < 1000; i++ {
		go func(parent context.Context) {
			ctx, cancel := context.WithCancel(parent)
			defer cancel()
			metautils.SetSingle(ctx, "key", "val")
		}(parent)
	}
}
```
The idea is that I receive gRPC request to service A which then calls concurrently multiple services (let's say B, C and D). I re-use parent context but I set some timeout for those requests. Connections between A and B-D are using retry logic from this repository (5 retries, 1 second timeout). So the race is in `metautils.SetSingle()` where multiple writes are performed on metadata map (storing x-retry-attempty header). Is it intended to not work concurrently or I'm doing something wrong? Above example is narrowed down to calling `metautils.SetSingle()` as it's not easy to reproduce, but I can prepare more adequate example if needed.

**Comment by krzysztofdrys** [comment]
Hi, I work in the same team as @viru.

I think I know the cause of this problem.

Comment on `metadata.FromContext` says:

> // FromContext returns the MD in ctx if it exists.
> // The returned md should be immutable, writing to it may cause races.
> // Modification should be made to the copies of the returned md.

The last advice is violated in `metadata.SetSingle`: https://github.com/mwitkow/go-grpc-middleware/blob/master/util/metautils/single_key.go#L43 . This causes multiple writes race condition in access to metadata map.

A simple fix would be to deep-copy map either in `metadata.SetSingle` (to make change more local) or in `metadata.FromContext` (to prevent similar problems in the future). 

Should we can prepare a PR implementing one of those solutions?

**Comment by viru** [comment]
`metadata.FromContext` is in gRPC package, so probably `metautils.SetSingle` is better place for a fix :)

**Comment by mwitkow** [comment]
@krzysztofdrys agreed about the race condition in the retry logic. It should copy the `Metadata` of the upcoming request. 

I'm actually thinking of introducing a `metautil.Inherit` which will create a new MD and only copy some pre-defined headers over (like the `:authorization` bearer token). And then these `metautil`, should modify that one in place.

**Comment by mwitkow** [comment]
In the mean time, can we make the retry logic make a copy of the metadata explicitly to fix your immediate issue?

**Comment by krzysztofdrys** [comment]
@mwitkow I am afraid, that I don't know enough about gRPC to validate if this is a good idea.

Having said that I read in the [documentation](http://www.grpc.io/docs/guides/wire.html) that:
> Custom-Metadata is an arbitrary set of key-value pairs defined by the application layer. Aside from transport limits on the total length of HTTP2 HEADERS the only other constraint is that header names starting with “grpc-” are reserved for future use.

So maybe `metautil.Inherit` should copy those as well?

Also, I am not sure I want `retry` interceptor to alter metadata. I expect it only to retry, there can be another interceptor for altering the metadata.

Finally,  `metautil.Inherit` would need to copy slices be safe from the race conditions. For solving our bug, it is enough to shallow-copy the metadata as in https://github.com/mwitkow/go-grpc-middleware/pull/22 .

> In the mean time, can we make the retry logic make a copy of the metadata explicitly to fix your immediate issue?
Yes, it would be great. Is there anything that should be added to https://github.com/mwitkow/go-grpc-middleware/pull/22 ?

**Comment by mwitkow** [comment]
@krzysztofdrys, I had to do some work on metadata this weekend, since upstream changed signatures anyway. There's now a `NiceMD` wrapper around `metadata.MD`, that adds convenience functions. One of them is `Clone`, which performs a correct deep-copy.

I moved the retry logic to use `Clone` for outgoing calls.

Please let me know if it fixes your issue.

Dzięki za bug report :)

**Comment by viru** [comment]
Yes, it fixes the problem :) Will close my PR. Thanks!
