### ISSUE TITLE
Is there any way I can ignore some function use authentication middleware?

### ISSUE THREAD

**Issue by sun-wenming** [grpc-ecosystem/go-grpc-middleware#213]
I don't know if this is correct. I have login, register, get the user's information function in the user grpc service. 
Get the user's information function use the auth middleware authentication token to get the necessary parameters to get the user information (such as user_id).
 Login, registration does not require the auth middleware authentication token .

Is there any way I can achieve it?

Like gin router:
Part of the group uses middleware, part of which is not use middleware.

```
                user := root.Group("/user")  // usergroup don't use auth token
		{
			user.POST("/register", api.Register)
                 }
               // apiv1
		apiv1 := root.Group("/api/v1")
		apiv1.Use(jwt.JWT())  // only apiv1  group use auth token
		{
			//  user
			user := apiv1.Group("/user-server")
			{        // get user info
				user.POST("/getUserInfo", api.GetUserInfo)
			}
		}
```

**Comment by dharmjit** [comment]
I am also looking for something like this in auth middleware

**Comment by sun-wenming** [comment]
@dharmjit   I am now solving the problem below.
```
var userServiceLogin = "/com.swm.svc.user.UserService/Login"
var userServiceRegister = "/com.swm.svc.user.UserService/Register"
var ignoreMethod = []string{userServiceLogin, userServiceRegister}

func myAuthFunction(ctx context.Context) (context.Context, error) {
	method, _ := grpc.Method(ctx)
	for _, imethod := range ignoreMethod {
		if method == imethod {
			return ctx, nil
		}
	}
}
```
