### ISSUE TITLE
grpclogger should implement LoggerV2 interface

### ISSUE THREAD

**Issue by kushp** [grpc-ecosystem/go-grpc-middleware#219]
Update https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/logging/zap/grpclogger.go#L20 to implement this interface https://github.com/grpc/grpc-go/blob/24b2fb8959201be9ce659bc87b0d590a34c67eae/grpclog/loggerv2.go#L30 instead of V1. Set verbosity based on `GRPC_GO_LOG_VERBOSITY_LEVEL` environmental variable.

I can take this on if we want to do it :)

**Comment by kushp** [comment]
I found this https://github.com/grpc-ecosystem/go-grpc-middleware/pull/144 would love if we merge it !

**Comment by kush-patel-hs** [comment]
#221 fixes this, closing
