### ISSUE TITLE
Privileges to allow more people to become maintainers.

### ISSUE THREAD

**Issue by domgreen** [grpc-ecosystem/go-grpc-middleware#231]
Raising an issue on multiple channels to try and get elevated privileges to help onboard a number of new maintainers to this repo.

cc @mwitkow @dinowernli  this is both for this repo and others in the grpc-ecosystem.

**Comment by mwitkow** [comment]
Who would you consider for inclusion here? :)

**Comment by domgreen** [comment]
Wooo :wave:  could you add @bwplotka and @johanbrandhorst into this as maintainers?

**Comment by bwplotka** [comment]
@mwitkow is alive????? :heart:

**Comment by mwitkow** [comment]
Yeah, I'm alive. Sadly my current job doesn't lend to much coding.

@bwplotka, @johanbrandhorst, welcome aboard! (invites in your inbox)
