### ISSUE TITLE
Logrus payload logging: Allow gogo marshaller

### ISSUE THREAD

**Issue by petervandenbroek** [grpc-ecosystem/go-grpc-middleware#235]
The logrus payload interceptor doesn't use the same jsonpb marshaller as grpc-gateway, causing it to have problems with time.Time (*time.Time is not proto.Message panic).
This makes sense, since the payload interceptor can also be applied to the server.

However, it should be possible to override the marshaller with a different one.
The field [is already exported](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/logging/logrus/payload_interceptors.go#L18), but doesn't allow me to set it to [gogo/gateway's marshaller](https://github.com/gogo/gateway/blob/master/jsonpb.go#L20).

I don't mind fixing this myself via PR, but I'm not sure what the best approach would be.

**Comment by johanbrandhorst** [comment]
Hi Peter, thanks for your issue!

I think we could solve this by just changing the exported variable from a `jsonpb.Marshaler` to an interface that implements the `Marshal` function. Would you be interested in contributing that fix?

**Comment by johanbrandhorst** [comment]
Fixed in #236
