### ISSUE TITLE
All tests not cleared while trying to package to debian

### ISSUE THREAD

**Issue by adgai19** [grpc-ecosystem/go-grpc-middleware#239]
While trying to build package for debian I get following error.
https://paste.debian.net/1105874

**Comment by johanbrandhorst** [comment]
Strange, looks like a deadlock on line 91 of the interceptor_suite.go.

**Comment by bmon** [comment]
This was probably resolved in #316

**Comment by johanbrandhorst** [comment]
Lets hope so :)
