### ISSUE TITLE
How can i use custom error in my project ?

### ISSUE THREAD

**Issue by lypee** [grpc-ecosystem/go-grpc-middleware#246]

**Comment by lypee** [comment]
forvige my English is very poor ;

i already usr 	grpc1.StreamInterceptor(grpc_middleware.ChainStreamServer(
				grpc_recovery.StreamServerInterceptor(),
			)),
			grpc1.UnaryInterceptor(grpc_middleware.ChainUnaryServer(
				grpc_recovery.UnaryServerInterceptor(),
			)),
those two interceptor and want to change return error type to apapate custom error context in my project

**Comment by johanbrandhorst** [comment]
Do you want to customize the error produced when recovering a panic? I'm not sure I understand the question.

**Comment by johanbrandhorst** [comment]
I think this was covered by #247
