### ISSUE TITLE
go-grpc-middleware/auth

### ISSUE THREAD

**Issue by jonericcook** [grpc-ecosystem/go-grpc-middleware#253]
Hello,

I am curious if there is a way to create a auth function like this https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/auth/examples_test.go#L26 but have it know which grpc method is being called?

For example, in the CreateUser grpc method i dont want the auth function to check if there is a bearer token in the meta data. I hope im explaining it correctly.

Essentially, I would like to be able to do something like this: https://github.com/ardanlabs/service/blob/master/cmd/sales-api/internal/handlers/routes.go#L38
Certain methods are authenticated and some are not.

**Comment by johanbrandhorst** [comment]
You can get the current method name from the context using https://godoc.org/google.golang.org/grpc#Method. That way you can create a big switch statement inside your auth func.
