### ISSUE TITLE
Option to use original error message instead of generic interceptor messages

### ISSUE THREAD

**Issue by ubunatic** [grpc-ecosystem/go-grpc-middleware#258]
The ["finished unary call with code" message](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/3c51f7f332123e8be5a157c0802a228ac85bf9db/logging/zap/server_interceptors.go#L66) is not very helpful as main error message in error logs.
The actual error message is often more important.

Services should have the option to use the original error message as main `message` (in addition to adding structured `error` and `code` fields). The interceptor's own message if required at all could be added as `interception` context in this case.

This will make features that work mainly on the error message, such as [Datadog's pattern detection](https://docs.datadoghq.com/logs/explorer/patterns/) much more useful, without losing the benefits of structured logging.

**Comment by johanbrandhorst** [comment]
Which logger are you using? The code you linked uses `zap.Error` for the error, which presumably includes the error in the log line?

**Comment by ubunatic** [comment]
Yes, we are using zap logging, with the following options:
```go
import grpc_zap "github.com/grpc-ecosystem/go-grpc-middleware/logging/zap"
// ...
	zapOptions := append([]grpc_zap.Option{
		grpc_zap.WithCodes(errorToCode),
		grpc_zap.WithLevels(codeToLevel),
	}, opts.zapOptions...)
```

The errors we intercept are, e.g., the following:
```go
import "google.golang.org/grpc/status"
// ...
return nil, status.Error(codes.Internal, "internal error")
```

In Datadog this error will be visible as follows:
![image](https://user-images.githubusercontent.com/532284/73737216-800d7280-4742-11ea-9495-588b40469d66.png)

Datadog shows the actual error message as `desc = internal error` in the `error` field for each individual log entry, which you need to click on in the pattern search UI. Their pattern feature only finds log patterns in the text description that was eventually logged via the zap interceptor: `"finished unary call with code Internal"` -- excluding the content from the `error` field.

Actually, I am not 100% sure if this should be fixed in the zap interceptor. This was just my first pick where I found the `finished unary call` message string. Maybe we should just ask Datadog to provide an option to allow pattern search also in the `error` field.

**Comment by ubunatic** [comment]
Thx @tinogoehlert for your cool solution #284!
