### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bernerdschaefer** [grpc-ecosystem/go-grpc-middleware#259]
👋 Hello, would it be possible to cut a new release? A number of things have landed in master since the v1.1.0 release back in September of last year. We're particularly interested in having https://github.com/grpc-ecosystem/go-grpc-middleware/pull/242 included in a release version.

Thanks!

**Comment by johanbrandhorst** [comment]
Hi @bernerdschaefer! I've tagged v1.2.0 for you: https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/v1.2.0.

**Comment by bernerdschaefer** [comment]
Thanks @johanbrandhorst!
