### ISSUE TITLE
go-grpc-middleware.v2: Action Plan.

### ISSUE THREAD

**Issue by bwplotka** [grpc-ecosystem/go-grpc-middleware#275]
Hi :wave: 

We have tons of stuff to improve in this library and there wasn't really time for this. Let's do it finally! Let's maintain this issue as a single place to track our work. :muscle: cc @domgreen @johanbrandhorst @mwitkow 

The plan is to start from scratch in the `v2` branch. We will work in the background until it's done.

## Work Done

* [x] Started v2 branch, implemented all while leaving same API.  Assignee: @bwplotka 
* [x] Never again use those weird `module_names` :upside_down_face: [Done](https://github.com/grpc-ecosystem/go-grpc-middleware/pull/276)  Assignee: @bwplotka 
* [X] Multi-module architecture, allowing us to avoid dependency hell, but also retaining mono repo. Module structure: [Done](https://github.com/grpc-ecosystem/go-grpc-middleware/pull/276)  Assignee: @bwplotka 
    The key part is to make sure the core is never importing the provider's code. There has to be indirection. This way the lib has minimum dependencies possible, with core literally having core only. 

   If maintaining multi modules will be problematic, we can look into [modularise](https://github.com/Helcaraxan/modularise-example-core) cc @Helcaraxan

### Blockers:

* [ ] Do one more review of all interfaces we expose to check if we can simplify something. Assignee @johanbrandhorst 
* [ ] Upgrade gRPC and use https://godoc.org/google.golang.org/grpc#ChainUnaryInterceptor  Assignee: @bwplotka 
* [ ]  Upgrade golang/protobuf to v2. Same with gogo?  Assignee: @bwplotka
* [ ] Move to GitHub actions Assignee: @bwplotka 
* [ ] MIgration docs! 
* [ ] Start using `gorelease` (https://godoc.org/golang.org/x/exp/cmd/gorelease)
* [ ] Consider adding whitelist behaviour to auth interceptor: How to enable whitelist auth?
* [ ] Add tracing interface and move opentracing to provides. Add opentelemetry providers.
* [ ] Use the v2 in [Thanos](https://thanos.io) for first hand expierience in upgrading. Assignee: @bwplotka  

### Can be done in 2.x

* [ ] Move https://github.com/grpc-ecosystem/go-grpc-prometheus as another provider. Deprecate repo.
* [ ] Add [failin](https://github.com/thanos-io/thanos/blob/master/Makefile#L305)t to avoid not needed imports (e.g v1 packages)
* [ ] Move to more maintained validators
* [ ] Review if we can simplify retry internally
* [ ] Stale bot
* [ ] Dependabot

Any other ideas?

**Comment by brancz** [comment]
I have no strong opinion about essentially having a monorepo, but I do wonder what the benefit is. I think they were separate because they had nothing in common not even shared unit test framework or anything. So I wonder if it’s worth it considering that given that things become harder with modules...

More generally though I do think these things need a pretty major overhaul and would love to see that happen! :)

**Comment by bwplotka** [comment]
Thanks for the feedback!

> I have no strong opinion about essentially having a monorepo, but I do wonder what the benefit is. I think they were separate because they had nothing in common not even shared unit test framework or anything. 

Now (as you will see in https://github.com/grpc-ecosystem/go-grpc-middleware/pull/276) all middlewares with reuse the majority of its code. Same for test frameworks (: It will be then easier for all maintainers (including Dom, Johan) to understand Prometheus one.

> So I wonder if it’s worth it considering that given that things become harder with modules...

Yes, but in the same time we have to solve it for logrus, zap, go-kit and potentially other implementations (: So far it's quite easy to work with multiple modules, but let's see the pain points (:

**Comment by brancz** [comment]
Yeah loggers would all be in the same repo, I'm more thinking things that are more distinct like logging and metrics middleware. But as I said, I'm against trying this at all.

**Comment by bwplotka** [comment]
Not against you mean (:

**Comment by bwplotka** [comment]
Essentially this is only what all implementations (including Prometheus) will need to implement and test (!):

```
type ClientReportable interface {
	ClientReporter(ctx context.Context, typ GRPCType, serviceName string, methodName string) (Reporter, context.Context)
}

type ServerReportable interface {
	ServerReporter(ctx context.Context, typ GRPCType, serviceName string, methodName string) (Reporter, context.Context)
}

type Reporter interface {
	PostCall(error, time.Duration)

	PostMsgSend(error, time.Duration)
	PostMsgReceive(error, time.Duration)
}
```

**Comment by brancz** [comment]
> Not against you mean (:

whops, what a great typo.. :D fixed my comment

**Comment by bwplotka** [comment]
More TODOs:
* [ ] Upgrade gRPC and use https://godoc.org/google.golang.org/grpc#ChainUnaryInterceptor
* [ ]  Upgrade golang/protobuf

**Comment by bwplotka** [comment]
First to points are done thanks to this: https://github.com/grpc-ecosystem/go-grpc-middleware/pull/276

Added few more todos as well. Please propose PRs to v2 if you want to help :hugs:

**Comment by panshul007** [comment]
TODO suggestion:

`grpc_logrus.Decider` currently takes `fullMethodName string` and `err error` as parameters, that restricts us in filtering by only two arguments. Would be nice to get the `context` in this method, so that we can filter by more things, such as the IP address of requester.

**Comment by bwplotka** [comment]
Definitely a valid request. :+1:

**Comment by mattbailey** [comment]
I'd like to see an interceptor that uses `grpclog`

It might be effective to, instead of writing an interceptor for each log library, write one for `grpclog` and then write interface shims for log libraries to satisfy the `grpclog.LoggerV2` interface.

**Comment by bwplotka** [comment]
We already did that (:

**Comment by bwplotka** [comment]
See v2 branch

**Comment by bwplotka** [comment]
We had very productive Sync with @johanbrandhorst :hugs: 

Updated https://github.com/grpc-ecosystem/go-grpc-middleware/issues/275#issue-573259966 with up to date must-have and nice-to-have action items before 2.0! :muscle: 

Help wanted (:

**Comment by yashrsharma44** [comment]
> Upgrade golang/protobuf to v2. Same with gogo? Assignee: @bwplotka

We are looking to upgrade `golang/protobuf` to `v1.4.2` and `gogo/protobuf` to `v1.3.1`?

**Comment by johanbrandhorst** [comment]
I think we want to go to `google.golang.org/protobuf` `v1.20.0+`.

**Comment by bwplotka** [comment]
Yup. Yash can you help us ? (:

**Comment by yashrsharma44** [comment]
Sure 😁
I have installed the repo locally, and I would love trying to upgrade `google.golang.org/protobuf v1.20.0+`, and fix breaking tests

**Comment by irridia** [comment]
I'd like to use v2, but it's not usable with go modules. Is this an intentional hold-back of v2? Or is there some specific go.mod hackery that's required?

I'm thinking starting v2.0.0-rcN tagging would be very helpful until you're ready to go v2.0.0.

```
	github.com/grpc-ecosystem/go-grpc-middleware/v2: module github.com/grpc-ecosystem/go-grpc-middleware@latest found (v1.2.0), but does not contain package github.com/grpc-ecosystem/go-grpc-middleware/v2
```

**Comment by johanbrandhorst** [comment]
I've created another tag, looks like we bungled the last one: https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/v2.0.0-rc.1.

Can you try
```shell
$ go get github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.1
```

**Comment by nashikb** [comment]
Works, but would you mind creating a new tag on v2 HEAD (maybe v2.0.0-rc.2?) so I can pick up my zerolog merge? Thanks!

**Comment by irridia** [comment]
Works, but would you mind creating a new tag off of v2 HEAD ( v2.0.0-rc.2 maybe?) so I can pick up my zerolog merge? Thanks!

**Comment by irridia** [comment]
That helps, but the "submodules" are still wonky. They may each need tags of the form `providers/logrus/v2.0.0-rc.1`.

github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/logrus@v2.0.0-rc.1: module github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.1 found, but does not contain package github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/logrus

**Comment by johanbrandhorst** [comment]
Yeah I have no idea how the multi-module repo thing should be working. I defer to @bwplotka and @Helcaraxan

**Comment by Helcaraxan** [comment]
Each module requires a dedicated tag in the shape of `<repo-relative-path-to-module/<version>`, just like @irridia has given the example.

I see that at least there's the advantages that you are not using `replace` statement but this will have the consequence that you can't make simultaneous and related changes across module boundaries in a single commit.

@johanbrandhorst, @bwplotka are you still interested in trying out the `modularise` tool? If so I can try to make some time to set it up in your CI. It will however require the creation of one repo per split and I don't know what your policy & perspective on that would be.

**Comment by bwplotka** [comment]
Interesting. I think I would be up for `modularise` here. We are ok with having separate repos and modularise can help us with versioning those. The problem we are not org admin and we probably would need that first to create multiple split repos. :thinking: Unless we start new org or something. Am I right @Helcaraxan ?

I would also try to look on what's s the problem mentioned by @irridia, @irridia why cannot you just get `github.com/grpc-ecosystem/go-grpc-middleware/providers/zerolog/v2@v2.0.0-rc.0` This should work just fine :thinking:

**Comment by Helcaraxan** [comment]
For a starter I can do some work in a branch so that you can all check it out and observe the resulting repositories to see whether that is something you feel OK with. This will work in local-only mode so no need for remote repositories. Those will simply be created on the fly on disk.

After that, If it's indeed something you'd like to pursue we will indeed need to create those repositories in whatever org or place you deem satisfying.

As for @irridia it's not possible to get that module as that tag does not exist. There is no `providers/zerolog/v2.0.0-rc.0` tag on this repository, only a `v2.0.0-rc.0` which only applies to the root module.

**Comment by johanbrandhorst** [comment]
I'll create that tag now. We can discuss what to do long term.

**Comment by bwplotka** [comment]
Yes, let's do rc tags for major changes in provider and main module for now. 

> For a starter I can do some work in a branch so that you can all check it out and observe the resulting repositories to see whether that is something you feel OK with. This will work in local-only mode so no need for remote repositories. Those will simply be created on the fly on disk.

yes please :heart: If you have time !

**Comment by johanbrandhorst** [comment]
Can you try again @irridia? https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/providers%2Fzerolog%2Fv2.0.0-rc.0

**Comment by johanbrandhorst** [comment]
Not sure how to go get this tbh, @Helcaraxan any ideas?
```
$ go get github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog@providers/zerolog/v2.0.0-rc.0
go get github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog@providers/zerolog/v2.0.0-rc.0: github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog@providers/zerolog/v2.0.0-rc.0: invalid version: version "providers/zerolog/v2.0.0-rc.0" invalid: disallowed version string
$ go get github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog@v2.0.0-rc.0
go get github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog@v2.0.0-rc.0: github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog@v2.0.0-rc.0: invalid version: unknown revision v2/providers/zerolog/v2.0.0-rc.0
$ go get github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog
go get github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog: module github.com/grpc-ecosystem/go-grpc-middleware/v2@upgrade found (v2.0.0-rc.1), but does not contain package github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog
```

**Comment by bwplotka** [comment]
I would check something like `github.com/grpc-ecosystem/go-grpc-middleware/providers/zerolog/v2@v2.0.0-rc.0` ;p

**Comment by Helcaraxan** [comment]
There are multiple elements here. Your initial try out was too early and the module proxy had not yet seen the new tag, as I explained to @bwplotka earlier on in an issue on [his `bingo` tool](https://github.com/bwplotka/bingo/issues/11#issuecomment-636394868).

Doing
```
go get github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog@v2.0.0-rc.0
```
should now result in
```
go get github.com/grpc-ecosystem/go-grpc-middleware/providers/zerolog/v2@v2.0.0-rc.0: github.com/grpc-ecosystem/go-grpc-middleware/providers/zerolog@v2.0.0-rc.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

This is because your nested module files have incorrect [module paths](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/providers/zerolog/go.mod#L1).

Instead of
```
module github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog
```
it should be
```
module github.com/grpc-ecosystem/go-grpc-middleware/providers/zerolog/v2
```

The `/v2` suffix applies to the module, not the repository.

So in this case this means fixing those paths (for all the nested modules) via a PR and then tagging the resulting merged commit with `<relative-module-path>/v2.0.0-rc.1`.

**Comment by bwplotka** [comment]
Ya looks like we need to fix module indeed:

```
go get github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog@v2.0.0-rc.1
go get github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog@v2.0.0-rc.1: module github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.1 found, but does not contain package github.com/grpc-ecosystem/go-grpc-middleware/v2/providers/zerolog
```

**Comment by bwplotka** [comment]
I am chasing other things, if no one will propse PR to fix will do in 1-2h

**Comment by irridia** [comment]
FWIW, I've had luck with multiple modules in a repo, but non-nested and without the v2+ go module "feature". I did suspect that the /v2/ needs to be at the end of the nested modules, but I wasn't 100% sure it wasn't part of Go's Very Well Documented Module Magick. :-|

I tried playing around with this in my fork, but it got very complicated. I can also poke at it later today after I get some sleep.

**Comment by bwplotka** [comment]
Fixing modules in this Pr: https://github.com/grpc-ecosystem/go-grpc-middleware/pull/296

**Comment by XSAM** [comment]
I'd like to help this part.

> Add tracing interface and move opentracing to provides. Add opentelemetry providers.

**Comment by bwplotka** [comment]
Please help @XSAM (: 


Also @johanbrandhorst we were having an interesting discussion with @yashrsharma44 

For example, all our intercepters are using a solid reporter interface. Such a reporter is not really tied to gRPC which gives us a quick way to implement tripperware and middleware for pure HTTP code as well that ensure the same metric, logging, tracing and tags behavior among HTTP and gRPC. This, however, would mean that:

* `interceptors/logging` would need to be more agnostic to gRPC (e.g Code to Level might be int code, not `codes.Code` etc)
* we might want to even host HTTP version of interceptors. This sounds quite crazy and is far from scope of this library, but some sibling projects would make sense - as long as we allow reusing our "reporters" for both gRPC interceptors and HTTP middleware.

What do you think? (:

**Comment by johanbrandhorst** [comment]
I think there's a real danger of going to deep on abstractions. Lets keep it simple if we can.

**Comment by bwplotka** [comment]
Yes, especially now there is not much code. This is something to think
about. (: For now we plan to logging into Thanos directly and adjust for
HTTP.

**Comment by irridia** [comment]
Just FYI, I've been using the logging interceptors (zerolog specifically) in prod with zero issues.

**Comment by bwplotka** [comment]
Amazing, looking for more time to finish things up (: protobuf and grpc nearly updated to latest

**Comment by bwplotka** [comment]
I pulled all the tasks to separate issues, so the idea is for @yashrsharma44 to create GH project for virst v2 release and track outstanding items there. (:

**Comment by ash2k** [comment]
@bwplotka I'm glad to see v2 happening!

For metrics, have you considered using gRPC's [`stats.Handler`](https://godoc.org/google.golang.org/grpc/stats#Handler) (via [`grpc.StatsHandler()`](https://godoc.org/google.golang.org/grpc#StatsHandler) for server and [`grpc.WithStatsHandler()`](https://godoc.org/google.golang.org/grpc#WithStatsHandler) for dials) instead of interceptors?

**Comment by drewwells** [comment]
> Amazing, looking for more time to finish things up (: protobuf and grpc nearly updated to latest

Where is outstanding working being tracked? I was looking at the list in this issue and noticed some where already done like github-actions.

**Comment by codefromthecrypt** [comment]
Is it time for another release candidate? last was 9 months ago

**Comment by yashrsharma44** [comment]
> For metrics, have you considered using gRPC's stats.Handler (via grpc.StatsHandler() for server and grpc.WithStatsHandler() for dials) instead of interceptors?

@ash2k Is there any difference on using `StatsHandler` instead of the `interceptors` for gRPC Middlewares? Just curious to know more about them.

**Comment by ash2k** [comment]
@yashrsharma44 I'm not the best person to ask as I'm not a gRPC expert, but off the top of my head:

- I suppose if gRPC team introduced a special way to collect stats, the approach must have some clear benefits.
- Interceptors are invoked in some order. If an interceptor that sits before the stats interceptor aborts the request, then the stats interceptor does not get a chance to measure the call.
- It feels cleaner to use a separate API for stats if it's there than mixing it with interceptors.
- Less chance of incorrect interceptor ordering.
