### ISSUE TITLE
In some use cases, AuthFunc needs info.FullMethod

### ISSUE THREAD

**Issue by binhn** [grpc-ecosystem/go-grpc-middleware#280]
In some use cases, a service might require authentication for some RPCs and not some others. If we pass info.FullMethod to AuthFunc, it would be able to decide. The less desirable alternative is to pass AuthFunc to the AuthFuncOverride so that it may call AuthFunc if necessary. 

The info.FullMethod may be inserted into the context so that we don't have to change AuthFunc signature, which would allow the existing code to work without modification.

A not-so-ideal workaround is to split up the service to separate out those RPCs that don't require authentication into a different service. However, this would complicate the coding on the client side.

I can open a pull request if folks think this is useful.

**Comment by johanbrandhorst** [comment]
The method name is available from the grpc.Method function. I think that should work?

**Comment by binhn** [comment]
@johanbrandhorst Thanks. I tested that and works very well.
