### ISSUE TITLE
embed localhost.crt in test go files

### ISSUE THREAD

**Issue by drewwells** [grpc-ecosystem/go-grpc-middleware#285]
It's not currently possible to vendor the testing suite with `go mod`. This is because `go mod` does not import repos, it only imports go packages. The testing suite makes references to `testing/certs/localhost.{crt,key}` which are not imported.

**Comment by johanbrandhorst** [comment]
Thanks for the issue! This should be easily solvable by inlining the certs as strings as you imply. Would you be interested in contributing this fix?

**Comment by bwplotka** [comment]
Makes sense to me :+1: Help wanted. Preferably on `v2` branch please (: 

See: https://github.com/grpc-ecosystem/go-grpc-middleware/issues/275
