### ISSUE TITLE
Can we pass context to Limit() func?

### ISSUE THREAD

**Issue by annp1987** [grpc-ecosystem/go-grpc-middleware#288]
Should we pass context to[ Limit() ](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/ratelimit/ratelimit.go#L15) func interface? This will allow us to make ratelimit per user is easier. What do you think? or any advice?

**Comment by johanbrandhorst** [comment]
Hi Nguyen. I'm not sure I understand the issue. Maybe you could join the #grpc-gateway channel on Gophers Slack and we could discuss? This is not the right forum for these sort of questions.
