### ISSUE TITLE
Running make proto has some errors

### ISSUE THREAD

**Issue by yashrsharma44** [grpc-ecosystem/go-grpc-middleware#301]
While running `make proto`, I am facing some issues, here is a traceback - 
```
installing gogofast
generating code
~/golib/src/github.com/yashrsharma44/go-grpc-middleware/grpctesting/testpb ~/golib/src/github.com/yashrsharma44/go-grpc-middleware
~/golib/src/github.com/yashrsharma44/go-grpc-middleware
~/golib/src/github.com/yashrsharma44/go-grpc-middleware/grpctesting/gogotestpb ~/golib/src/github.com/yashrsharma44/go-grpc-middleware
github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.
fields.proto: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
Makefile:28: recipe for target 'proto' failed
make: *** [proto] Error 1
```

I looked into other resources and found that @johanbrandhorst has a blog on the issue - https://jbrandhorst.com/post/gogoproto/
But there wasn't any workaround for the above, hence I decided to post this issue and ask the maintainers :stuck_out_tongue:

**Comment by johanbrandhorst** [comment]
We try to do some magic to find the gogoproto path in your module cache:

https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/scripts/genproto.sh#L21-L25

Could you try and see what
```shell
$ GO111MODULE=on go list -f '{{ .Dir }}' -m github.com/gogo/protobuf
```
returns on your machine?

**Comment by yashrsharma44** [comment]
Sure, it returns -
```
/home/yash/golib/pkg/mod/github.com/gogo/protobuf@v1.3.1
```

**Comment by yashrsharma44** [comment]
Fixed
