### ISSUE TITLE
Validate request in stream interceptor

### ISSUE THREAD

**Issue by parmen789** [grpc-ecosystem/go-grpc-middleware#309]
Hello, I have a question, I want to validate requests via interceptors, I consider both non streaming and streaming RPCs, for non streaming I can use UnaryInterceptor which has a request as a parameter, but is there a way to obtain information from request in StreamInterceptor? UnaryInterceptor does not apply on streaming RPCs as far as I know and tried. I consider only server-side.

**Comment by johanbrandhorst** [comment]
https://pkg.go.dev/google.golang.org/grpc?tab=doc#StreamClientInterceptor explains that you can implement a custom `ClientStream` to intercept all IO being sent through the interceptor. I don't think we support this use case (yet?).

**Comment by powerman** [comment]
Any plans to add this interceptor?

**Comment by Lev1ty** [comment]
+1

**Comment by johanbrandhorst** [comment]
I believe this is implemented? https://github.com/grpc-ecosystem/go-grpc-middleware/tree/main/interceptors/validator
