### ISSUE TITLE
v2: Feature Request : Request/Response Logging

### ISSUE THREAD

**Issue by yashrsharma44** [grpc-ecosystem/go-grpc-middleware#310]
I am currently working on adding a logging feature of grpc, at the request/response level for [Thanos](https://github.com/thanos-io/thanos/pull/2694). I had a look at the [current logging](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/logging/interceptors.go) implementation, and I found that the we don't log at a level where we could access the req/resp object.

[Payload](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/logging/payload.go) implementation has the feature that I am looking for, but I want similar stuff _minus_ payload logging.

More technically, the current logging does not implement the [`PostMsgSend`](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/logging/interceptors.go#L53) and [`PostMsgRecv`](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/logging/interceptors.go#L55) method, so I wanted to extend the reporter by adding implementation logic for `PostMsgSend` and `PostMsgRecv`.
* I guess having a new reporter would be more beneficial for not breaking backwards compatibility for the current logging implementation.
* Also, the [WithDecider](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/logging/options.go#L51) method only filters the logging based on error and method/service name, while I also wanted to filter out the logging based on the req/resp object.

I was willing to work on such implementation, so I wanted some suggestions / green flag, if adding this would be acceptable.

Ping @johanbrandhorst

**Comment by johanbrandhorst** [comment]
That sounds great! Lets put together a PR and go from there.

**Comment by bwplotka** [comment]
This is great, but I would rather work on improving our reporter than creating separate one. What do you think? (:

**Comment by yashrsharma44** [comment]
The only drawback of adding the new functionality is that the current behaviour of logging would change, which might be backwards compatible.
But if we are okay with that, we might move forward with this suggestion.

**Comment by shouichi** [comment]
Filtering based on request field would be great. For example, logging login request but filter out the password field.
