### ISSUE TITLE
How to send in stdout log when retries query (grpc_retry).

### ISSUE THREAD

**Issue by mirecl** [grpc-ecosystem/go-grpc-middleware#315]
Hi.
Pls asked me, how to send in stdout log when retry send data?

**Comment by johanbrandhorst** [comment]
Looks like it should be possible to do something with the trace logging: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/retry/retry.go#L321. Not sure we support this natively otherwise.

**Comment by bwplotka** [comment]
Yea, I think you can wrap the tracer for this, but this seems like rare use case: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/retry/retry.go#L316

**Comment by bwplotka** [comment]
Let's close unless it's still not clear(:
