### ISSUE TITLE
grpc_recovery - panic(nil) handled strangely

### ISSUE THREAD

**Issue by venezia** [grpc-ecosystem/go-grpc-middleware#328]
If a function calls `panic(nil)`, instead of say `panic(fmt.Sprintf("oh noes!"))` within the scope of grpc_recovery, the panic is caught, but instead of an error code being returned to the client an empty response and no error code is returned.

To reproduce:
* Have a gRPC RPC method call `panic(nil)` right away
* Enable grpc_recovery with no specific options - `grpc.UnaryInterceptor(grpc_middleware.ChainUnaryServer(grpc_recovery.UnaryServerInterceptor()))`
* See that the grpc call returns with empty result and no error
* Update gRPC RPC method call to `panic(fmt.Sprintf("oh noes!"))`
* See that the grpc call now returns an error code 13 with "oh noes!" with the error string

I know that panics should not have a nil message, but I feel that this case should be supported, in part because a library could do it and it is valid go code.  The panic is recovered, it just does not communicate to the client that an error has occurred which could be less than ideal.

Full disclosure - I found this error by testing out grpc_recovery with a poorly written (nil) panic and not getting the result I expected.

**Comment by nvx** [comment]
I'm not entirely sure if this is possible. Calling recover() inside a deferred func() only returns a single value as per https://godoc.org/builtin#recover

I can't think of a way to differentiate between panic(nil) and a non-panic return short of introspecting the call stack to find calls to panic(), but I suspect this would be a non-trivial performance hit.

It feels to me like Golang should handle panic(nil) as an invalid operation instead raising an independent panic indicating misuse of panic, similar to how divide by zero/etc is handled.

**Comment by bwplotka** [comment]
Interesting (: Let's investigate a bit, are we sure `recover` does not pass us `nil`?

**Comment by bwplotka** [comment]
Let's fix on `v2 ` as well.

**Comment by ivan-valkov** [comment]
I believe this is handled now in https://github.com/grpc-ecosystem/go-grpc-middleware/pull/281
We should close this issue

**Comment by johanbrandhorst** [comment]
Sounds good to me!
