### ISSUE TITLE
please cut a release

### ISSUE THREAD

**Issue by dmitris** [grpc-ecosystem/go-grpc-middleware#333]
Could you please cut a release off the master for the fixes to #324 (PR #325)? This would allow users like us to replace temporary vendored "hot-fix" copies with a normal module version pointer in `go.mod`.  Thanks.

**Comment by johanbrandhorst** [comment]
Done https://github.com/grpc-ecosystem/go-grpc-middleware/compare/v1.2.1...v1.2.2
