### ISSUE TITLE
v2: Replace our chaining of interceptors with newest gRPC ones.

### ISSUE THREAD

**Issue by bwplotka** [grpc-ecosystem/go-grpc-middleware#342]
See: https://godoc.org/google.golang.org/grpc#ChainUnaryInterceptor

Blocked on upgrade PR: https://github.com/grpc-ecosystem/go-grpc-middleware/pull/321

Pulled from https://github.com/grpc-ecosystem/go-grpc-middleware/issues/275 for visibility.

Blocker for v2.

**Comment by curiousleo** [comment]
Looks like this has been resolved by #385 and can be closed?

**Comment by johanbrandhorst** [comment]
Sounds good to me!

**Comment by bwplotka** [comment]
I haven't seen this fix 😱 Amazing, thanks! Super cool, this brings us almost ready for `v2` release (: Thank you so much!

**Comment by ecordell** [comment]
grpc's `ChainUnaryInterceptor` returns a ServerOption, not an interceptor, so it can't be used to build chains that are also interceptors (to be included in other chains).

We use this behavior in [spicedb](https://github.com/authzed/spicedb) to associate default interceptors with service implementations: 

https://github.com/authzed/spicedb/blob/500d9dcbf376a545a96c0d0b62340e7f1c653e85/internal/services/v1/relationships.go#L58-L68

which are then included in bigger interceptor chains for actually serving, based on startup options, etc. 

It seems pretty handy to have `func(...Interceptor) Interceptor` in this library - any chance we could bring it back for v2? Or do you think it would be better to see if grpc-go could have an option to change the return type of the `Chain` fns?

**Comment by johanbrandhorst** [comment]
Hi Evan. I think we're trying to remove as much API as possible at this point, since we're cutting a new major. Do you think you could refactor your code or re-implement the old code in your code base? If we get more requests for this we can always add it later.
