### ISSUE TITLE
v2: Move https://github.com/grpc-ecosystem/go-grpc-prometheus as another provider. Deprecate repo.

### ISSUE THREAD

**Issue by bwplotka** [grpc-ecosystem/go-grpc-middleware#346]
This was discussed initially with @brancz https://github.com/grpc-ecosystem/go-grpc-middleware/issues/275#issuecomment-593261947

I think the decision is to incorporate this Prometheus middleware here. 

Not a blocker for first v2 release.

**Comment by brancz** [comment]
Feel free to archive the other repo once this is done I would say.

**Comment by ash2k** [comment]
I'm looking forward to using the refreshed integration!

**Comment by bwplotka** [comment]
cc @yashrsharma44

**Comment by yashrsharma44** [comment]
This issue for addressed by #379 closing this hence.
