### ISSUE TITLE
v2: Create Method Deciding / Filtering interceptor.

### ISSUE THREAD

**Issue by bwplotka** [grpc-ecosystem/go-grpc-middleware#350]
Right now all interceptors are global - per the whole server. This is nice, as it creates some consistency, but sometimes you want to skip certain methods OR only use some interceptor for this.

Wonder if we can create another interceptor for this instead of recreating the decider options for every interceptor: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/73cf2ae9d89195f8a2d4860d7b3f2bc4871d9ec7/interceptors/logging/logging.go#L67 WDYT? (:

**Comment by johanbrandhorst** [comment]
Nah, personally I think this is too much complexity in this library.

**Comment by bwplotka** [comment]
:+1:
