### ISSUE TITLE
Enhance dummy rate limit interceptor we have.

### ISSUE THREAD

**Issue by bwplotka** [grpc-ecosystem/go-grpc-middleware#351]
Problem: Current limiter interface does not care about method, metadata (e.g user). So it blocks basic multitenancy use cases. 

We also cannot just return something like `RateLimited` status for `client` base queuing and retrying logic if needed (: 

Let's think it about it more. Also worth to check https://github.com/envoyproxy/ratelimit

cc @yashsharma44

**Comment by yashrsharma44** [comment]
Is it fixed by #386 or do we want to add more implementations(provider) for this?

**Comment by bwplotka** [comment]
This is done thanks to @MalloZup PR indeed 💪🏽
