### ISSUE TITLE
Client Logging Interceptor defaults behave incorrectly

### ISSUE THREAD

**Issue by dackroyd** [grpc-ecosystem/go-grpc-middleware#36]
The client variants of the logging interceptors were added in https://github.com/grpc-ecosystem/go-grpc-middleware/pull/33. Following this change, logging interceptors do not behave correctly in their default configurations i.e. without specifying `Options` as overrides

### Logrus (server & client interceptors):
Unless `WithLevels(...)` is specified as an option, calls to the logging interceptor _panic_, as `o.levelFunc` is `nil`

### Zap (client interceptor only):
Unless `WithLevels(...)` is specified as an option, calls to the logging interceptor are logged at the incorrect levels as the default is the `DefaultCodeToLevel` for both server and client interceptors

**Comment by mwitkow** [comment]
That was affecting master since https://github.com/grpc-ecosystem/go-grpc-middleware/pull/33 until https://github.com/grpc-ecosystem/go-grpc-middleware/pull/35. Now it's fixed, and the tests of #35 check the defaults.

Sorry about that.

**Comment by dackroyd** [comment]
Defaults look good again after https://github.com/grpc-ecosystem/go-grpc-middleware/pull/35 was merged, thank you!
