### ISSUE TITLE
How to set Interceptor for only few routes

### ISSUE THREAD

**Issue by vijay8059** [grpc-ecosystem/go-grpc-middleware#360]
Hi, 
I have a requirement where i don't want to execute interceptors for all the rpc methods, How i can set the interceptors conditionally?
looking for something similarly. 
https://chenyitian.gitbooks.io/gin-tutorials/content/tdd/21.html
execute interceptors for few routes

**Comment by johanbrandhorst** [comment]
An interceptor by definition wraps all requests. You can use https://pkg.go.dev/google.golang.org/grpc#Method to find the current method in an interceptor.
