### ISSUE TITLE
Make rate_limit aware of context

### ISSUE THREAD

**Issue by xinxiao** [grpc-ecosystem/go-grpc-middleware#365]
Add context as a parameter to rate limit interface

https://github.com/grpc-ecosystem/go-grpc-middleware/blob/c05cb4087a4d39efca33c77cd505d0817d0b253a/ratelimit/ratelimit.go#L15

**Comment by johanbrandhorst** [comment]
Makes sense, would you be willing to contribute this to the v2 branch?

**Comment by xinxiao** [comment]
@johanbrandhorst PR created

**Comment by johanbrandhorst** [comment]
Fixed in #367
