### ISSUE TITLE
logrus.SetLevel() has no effect after ReplaceGrpcLogger

### ISSUE THREAD

**Issue by kochurovro** [grpc-ecosystem/go-grpc-middleware#368]
Hi. 
The Entry.Level will be 0 everytime after that code
```
grpclog.SetLoggerV2(&logrusGrpcLoggerV2{
		logger.WithField("system", SystemField),
	})
```

```
func Test_logrusGrpcLoggerV2_V(t *testing.T) {
    log := logrus.New()
    log.SetLevel(logrus.WarnLevel)
    grpc_logrus.ReplaceGrpcLogger(logrus.NewEntry(log))
    println(fmt.Sprintf("compare with 3 result is %v",grpclog.V(3)))
    println(fmt.Sprintf("compare with 0 result is %v",grpclog.V(0)))
}
```
Could you clarify it is correct result of V method?

**Comment by johanbrandhorst** [comment]
:man_shrugging: I'm not sure the person who wrote this code is still maintaining the repo, so if you think it's wrong lets put together a failing test case and get a fix in :).

**Comment by kochurovro** [comment]
@johanbrandhorst thank you for the merge! 

This update doesn't work for second version so I am going to close issue.
