### ISSUE TITLE
retry: add option for generic hook on retry

### ISSUE THREAD

**Issue by howardjohn** [grpc-ecosystem/go-grpc-middleware#375]
This is extremely similar to https://github.com/grpc-ecosystem/go-grpc-middleware/issues/356; happy to merge in with that one if it makes more sense.

It would be useful to have a generic callback when a retry is triggered. This will allow us to not only add our own logging, but also handle some metrics. Its also generic, so if someone has some other requirements they could add whatever hooks they need

**Comment by howardjohn** [comment]
Currently hacking this with 

```go
func wrapBackoffWithMetrics(bf retry.BackoffFunc) retry.BackoffFunc {
	return func(attempt uint) time.Duration {
		wait := bf(attempt)
		log.Warnf("request failed, starting attempt %d in %v", attempt, wait)
		monitoring.NumOutgoingRetries.Increment()
		return wait
	}
}
```

Seems to work, the downsides are we don't get access to the error, and it feels hacky

**Comment by johanbrandhorst** [comment]
I like this proposal better, since it'll allow the user to do whatever they want when a retry happens, but we should probably still reword the first issue along the lines of this one rather than closing that one. So I'll update that issue and close this one.
