### ISSUE TITLE
#293 Ambiguous import issues when pinning grpc to <v1.30 

### ISSUE THREAD

**Issue by drewwells** [grpc-ecosystem/go-grpc-middleware#377]
google.golang.org/grpc v1.30+ broke a lot of contracts. As a result, we have been unable to upgrade to it and are stuck on v1.29.1. I'm seeing issues importing go-grpc-middleware, after some digging the issues are related to these changes #293. The test example is using google.golang.org/grpc/examples which imports [bleeding edge grpc](https://github.com/grpc/grpc-go/blob/master/examples/go.mod#L13) so we can not import it.

Could we stand up our own example proto to perform these simple tests? It will make this project more portable and support us poor saps unable to upgrade grpc.

Here's the error from `go mod tidy`
```
        github.com/infobloxopen/atlas-claims imports
        github.com/grpc-ecosystem/go-grpc-middleware/auth tested by
        github.com/grpc-ecosystem/go-grpc-middleware/auth.test imports
        google.golang.org/grpc/examples/helloworld/helloworld: ambiguous import: found package google.golang.org/grpc/examples/helloworld/helloworld in multiple modules:
        google.golang.org/grpc v1.34.0 (/home/drew/pkg/mod/google.golang.org/grpc@v1.29.1/examples/helloworld/helloworld)
        google.golang.org/grpc/examples v0.0.0-20201209011439-fd32f6a4fefe (/home/drew/pkg/mod/google.golang.org/grpc/examples@v0.0.0-20201209011439-fd32f6a4fefe/helloworld/helloworld)
```

Related #293

**Comment by johanbrandhorst** [comment]
So we're depending transitively on bleeding edge grpc because we import the examples, which is its own module, which imports bleeding edge grpc? What a mess. Sounds like we should remove whatever example import we're depending on. Could you help get that done?
