### ISSUE TITLE
Misleading comments in the interceptor file

### ISSUE THREAD

**Issue by yashrsharma44** [grpc-ecosystem/go-grpc-middleware#378]
Both the server and client files for interceptor contains a misleading comment - 
[Link](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/client.go#L4)
```
// gRPC Prometheus monitoring interceptors for client-side gRPC.
```
[Link](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/server.go#L4)
```
// gRPC Prometheus monitoring interceptors for server-side gRPC.
```

Prometheus shouldn't be present, since this is interceptor for `go-grpc-middlewares`.

**Comment by bwplotka** [comment]
PR's welcome! (:

**Comment by bwplotka** [comment]
(I was basing this on Prometheus interceptors that's why)

**Comment by yashrsharma44** [comment]
#424 addresses the changes :)
