### ISSUE TITLE
v2: Switch `grpclog.Infof` with something non-global

### ISSUE THREAD

**Issue by bwplotka** [grpc-ecosystem/go-grpc-middleware#391]
There is no way to control this on instance lvl, it's only global. Let's fix this.

e.g `grpclog.Infof("grpc_opentracing: failed parsing trace information: %v", err)` in `tracing` package.

Not blocking v2 release, we can do later.

**Comment by berenda-andrey** [comment]
@bwplotka I have created the pr
could you watch it?

**Comment by bwplotka** [comment]
Thanks for the PR, but this is now done, because we decided to remove opentracing completely. It is deprecated (if needed opentracing from v1 can be used) and otherwise users can use otlpgrpc (: 

Thanks anyway, and sorry we didn't notice this earlier!
