### ISSUE TITLE
v2: Move `metautils` to it's own package

### ISSUE THREAD

**Issue by bwplotka** [grpc-ecosystem/go-grpc-middleware#392]
This is the package that allows to pass things across gRPC peers. You mention @johanbrandhorst some other methods for this 🤔 Is there something or should we maintain it here?

**Comment by johanbrandhorst** [comment]
I think this is written on top of gRPC metadata? It should still be relevant in that case.

**Comment by bwplotka** [comment]
In this indeed.

**Comment by gunadhya** [comment]
Hi @bwplotka and @johanbrandhorst, I'd like to work on this issue. Just to confirm the metautils needs to be moved outside utils to the root and the [references ](https://github.com/grpc-ecosystem/go-grpc-middleware/search?q=util+metautils) need to be updated right?

**Comment by bwplotka** [comment]
Correct, just while you are doing this, can you just double check if all method names, comments make sense too? Would be nice to clean this before v2 release (while we can) 🤗 

Also some better package name might be needed. The `metadata` is the original name on gRPC package that this one wraps. `niceMD` is not the best name as .... what nice means? Let's be more focused. Some name that exactly tells what it's added on top of original metadata package would be amazing (don't have idea right now). Feel free to propose something in the PR @gunadhya 🤗 

Thanks!

**Comment by bwplotka** [comment]
Oh, and make you to start from `v2` branch and you point your PR to `v2` (it has to be done manually for now on GitHub UI)

**Comment by gunadhya** [comment]
Some changes to `metautils` were made since `v2` got created as shown here -> [`master`](https://github.com/grpc-ecosystem/go-grpc-middleware/commits/master/util/metautils)  and [`v2`](https://github.com/grpc-ecosystem/go-grpc-middleware/commits/v2/util/metautils)
I found [**this**](https://stackoverflow.com/questions/2668886/git-copy-all-files-in-a-directory-from-another-branch) and was just wondering if  `git checkout master -- dirname` is the right way to update the package files or is there a better way to do this?

**Comment by yashrsharma44** [comment]
You need to rebase your branch and start working on top of the current changes.
More info on rebasing - https://github.com/efficientgo/tools#module-githubcomefficientgotoolscopyright

**Comment by rahulkhairwar** [comment]
Hi @bwplotka , as the issue has been stale for a while, I've raised a [PR](https://github.com/grpc-ecosystem/go-grpc-middleware/pull/474) for this change.

Please have a look and let me know if there are any suggested changes.

**Comment by bwplotka** [comment]
Fixed by https://github.com/grpc-ecosystem/go-grpc-middleware/pull/474
