### ISSUE TITLE
v2: Consider moving to `With` for clients interceptor instead of explicit Server/Client

### ISSUE THREAD

**Issue by bwplotka** [grpc-ecosystem/go-grpc-middleware#393]
v2 is a good moment to rethink Server vs Client naming. Looks like gRPC sticks to just `Interceptor` for server and `WithInterceptor` for clients... not sure if that makes sense though 🤔 Any preferences @johanbrandhorst ?

![image](https://user-images.githubusercontent.com/6950331/106368688-6f86dc80-6343-11eb-99c9-199680ceefa1.png)

**Comment by johanbrandhorst** [comment]
I agree we should just follow that precedence when it comes to naming.

**Comment by bwplotka** [comment]
After rethinking... This might be confusing for existing middleware users (:
