### ISSUE TITLE
passing `err.Error()` to the format string of `grpc.Errorf` allows format string injection

### ISSUE THREAD

**Issue by petermattis** [grpc-ecosystem/go-grpc-middleware#396]
https://github.com/grpc-ecosystem/go-grpc-middleware/blob/fab13c27ec1d74ec053740349a01efaae87e5aa4/validator/validator.go#L25

I think the call to `grpc.Errorf` should look something like `grpc.Errorf(codes.InvalidArgument, "%s", err.Error())`. Alternately, you could call `status.Error` instead since `grpc.Errorf` is a wrapper around `status.Errorf`.

**Comment by petermattis** [comment]
The title isn't quite accurate. I don't think this causes any problems in practice beyond a confusing error string, but it deserves to be fixed.

**Comment by johanbrandhorst** [comment]
Good spot, that is indeed wrong, would you like to contribute a fix?
