### ISSUE TITLE
For Payload Logging Interceptors, consider allowing deciding on both request and response

### ISSUE THREAD

**Issue by CyborgMaster** [grpc-ecosystem/go-grpc-middleware#400]
In our app, we have "list" endpoints that return a list of many objects, e.g. `ComponentService.List`.  The responses to these requests may be quite large and therefore we do not want to log them.  I saw that these interceptors take a decider that conditionally skips logging

``` go
func PayloadUnaryServerInterceptor(logger *zap.Logger, decider grpc_logging.ServerPayloadLoggingDecider) grpc.UnaryServerInterceptor
```

and was planning on using this to skip these requests, but ran into a second problem.  Because these endpoints have the potential to return a lot of data, they also have the potential to be slow, so when a slow request comes in we like to check the logs to see the request contents to understand what they asked for.  However, if we use the decider to block logging, we block it for both the request and the response.  I need to log the request, but not the response.  

I've solved it our app by creating a custom interceptor based on `PayloadUnaryServerInterceptor` that takes two deciders, one for the request and one for the response.

``` go
func PayloadUnaryServerInterceptor(
	logger *zap.Logger,
	requestDecider grpc_logging.ServerPayloadLoggingDecider,
	responseDecider grpc_logging.ServerPayloadLoggingDecider,
) grpc.UnaryServerInterceptor {
	return func(
		ctx context.Context,
		req interface{},
		info *grpc.UnaryServerInfo,
		handler grpc.UnaryHandler,
	) (interface{}, error) {
		logRequest := requestDecider(ctx, info.FullMethod, info.Server)
		logResponse := responseDecider(ctx, info.FullMethod, info.Server)

		if !logRequest && !logResponse {
			return handler(ctx, req)
		}

		// Use the provided zap.Logger for logging but use the fields from context.
		logEntry := logger.With(append(serverCallFields(info.FullMethod), ctxzap.TagsToFields(ctx)...)...)

		if logRequest {
			logProtoMessageAsJson(
				logEntry,
				req,
				"grpc.request.content",
				"server request payload logged as grpc.request.content field",
			)
		}
		resp, err := handler(ctx, req)
		if logResponse && err == nil {
			logProtoMessageAsJson(
				logEntry,
				resp,
				"grpc.response.content",
				"server response payload logged as grpc.response.content field",
			)
		}
		return resp, err
	}
}
```

I would love to see something like this in the official library as I don't imagine our use case is unique.  I didn't open a PR because this would be a breaking change to the API so I'm not sure how you wanted to handle it.

**Comment by bwplotka** [comment]
Sounds good. There is good opportunity to do it right: We work on `v2` branch. 

Can you propose a solution to `v2` branch? 🤗 We are close to releasing so if we want something breaking, we need to act.. now (:

**Comment by CyborgMaster** [comment]
I plan to open a PR on the v2 branch today.

**Comment by CyborgMaster** [comment]
Sorry, I spent a few minutes on it, and I'm not going to be able to do it today.  I was hoping it was going to be just drop in my code, but of course there are the tests and this really should be done for all three payload interceptors to make them consistent.  I may take another look at carving out the time when our next push is done in a week or so.

**Comment by yashrsharma44** [comment]
I think issue would be potentially solved by this - #442

**Comment by CyborgMaster** [comment]
This looks it it would solve it.  Once that is merged and we can use it, I'll switch over to that!  Thanks!

**Comment by yashrsharma44** [comment]
#442 solves the requirements of this issue. Let me know if anything else is required, closing this for now.
