### ISSUE TITLE
Auth middleware for more than one service per grpc server

### ISSUE THREAD

**Issue by a-urth** [grpc-ecosystem/go-grpc-middleware#401]
I have two grpc services per one server - service with business logic and grpc_health service

```go
grpcServer := grpc.NewServer(
	grpc.UnaryInterceptor(
		grpc_middleware.ChainUnaryServer(
			grpc_prometheus.UnaryServerInterceptor,
			grpc_auth.UnaryServerInterceptor(grpcz.BasicTokenAuth(cfg.Token)),
			apmgrpc.NewUnaryServerInterceptor(apmgrpc.WithRecovery()),
		),
	),
)

grpc_prometheus.EnableHandlingTimeHistogram()
grpc_prometheus.Register(grpcServer)

pb.RegisterIssuerServer(grpcServer, grpcSrv)

grpc_health_v1.RegisterHealthServer(grpcServer, healthOverride{health.NewServer())

...

type healthOverride struct {
	grpc_health_v1.HealthServer
}

func (ho *healthOverride) AuthFuncOverride(ctx context.Context, mn string) (context.Context, error) {
	return ctx, nil
}
```

I implement `AuthFuncOverride` for grpc_health service (through wrapper), since I don't want it to work with auth

And this override doesn't work for me. So I wonder whether it should work like that in general.

Although in documentation is stated that auth override can be used per service (https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/auth#ServiceAuthFuncOverride) in given example there is only service used (https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/auth#example-package-ServerConfigWithAuthOverride)

**Comment by johanbrandhorst** [comment]
It should work per-type that implements the interface at registration time, we perform a type assertion in the code (https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/auth/auth.go#L39). You can try debugging the implementation to see what the type of `info.Server` is, but I believe this should work.

**Comment by a-urth** [comment]
Thats a terrible mistake from my side - I should've pass pointer to wrapper structure instead of structure itself. Thats why it failed check for interface implementation.

Thank You!
