### ISSUE TITLE
gRPC v1.30+ support?

### ISSUE THREAD

**Issue by kevmo314** [grpc-ecosystem/go-grpc-middleware#404]
Is there any plan for supporting newer versions of gRPC? I see the version was intentionally pinned to v1.29, what needs to be done to update?

**Comment by johanbrandhorst** [comment]
We're working on v2 to support gRPC v1.30+. See https://github.com/grpc-ecosystem/go-grpc-middleware/issues?q=is%3Aissue+is%3Aopen+v2+label%3Av2 for open issues.

**Comment by kevmo314** [comment]
Awesome, thank you!
