### ISSUE TITLE
Let's pass context in v2's interceptor.

### ISSUE THREAD

**Issue by j2gg0s** [grpc-ecosystem/go-grpc-middleware#409]
Why we don't pass context as first argument in `interceptor.Reporter`?

```
type Reporter interface {
	PostCall(ctx context.Context, err error, rpcDuration time.Duration)
	PostMsgSend(ctx context.Context, reqProto interface{}, err error, sendDuration time.Duration)
	PostMsgReceive(ctx context.Context, replyProto interface{}, err error, recvDuration time.Duration)
}
```

**Comment by yashrsharma44** [comment]
I think this would be a nice addition to the interceptor pattern - 
* We can pass more _context_ to the middlewares
* The middleware deciders - (https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/logging/interceptors.go#L48) - can make more intelligent decisions based on the context variables.

+1 for this.

**Comment by yashrsharma44** [comment]
Tagging @johanbrandhorst @bwplotka for some opinions about this 😄 .

**Comment by johanbrandhorst** [comment]
Sounds good to me too

**Comment by bwplotka** [comment]
Great point. As long as it's not abused... but I can see report checking extra context from request so why not!

**Comment by bwplotka** [comment]
Why is this a requirement though? Isn't it enough if the whole reporter struct has the request context? Do we need to have it on every passed thing? It's the same context, no?

**Comment by bwplotka** [comment]
Essentially your implementation creates reports using https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/reporter.go#L63 and there is request context passed there. 🤔
