### ISSUE TITLE
v2: logging provider: klog/v2

### ISSUE THREAD

**Issue by m-yosefpor** [grpc-ecosystem/go-grpc-middleware#430]
As most of k8s related tools are using klog as a standarad logging tools, it's great if we consider adding klog/v2 provider in v2 natively.

**Comment by johanbrandhorst** [comment]
That sounds like a great idea, would you be willing to contribute this?

**Comment by m-yosefpor** [comment]
> That sounds like a great idea, would you be willing to contribute this?

Sure I'll create a PR.

**Comment by bwplotka** [comment]
PR wanted, but this is not v2 blocker though, we an add later.

**Comment by bwplotka** [comment]
Fixed by https://github.com/grpc-ecosystem/go-grpc-middleware/pull/510
