### ISSUE TITLE
openmetrics: context.Background() breaks grpc context helper functions

### ISSUE THREAD

**Issue by amenzhinsky** [grpc-ecosystem/go-grpc-middleware#433]
[This](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/providers/openmetrics/reporter.go#L112) breaks functions that retrieve information from incoming context, e.g. `grpc.ServerTransportStreamFromContext`, `grpc.Method`, etc.

**Comment by johanbrandhorst** [comment]
Hm, yes that is not great at all. @yashrsharma44 @bwplotka do we have access to the incoming context here? Feels very wrong to break the context chain.
