### ISSUE TITLE
Slack link does not work anymore

### ISSUE THREAD

**Issue by olivierlemasle** [grpc-ecosystem/go-grpc-middleware#437]
The [Slack link](https://slack.com/share/IRUQCFC23/9Tm7hxRFVKKNoajQfMOcUiIk/enQtODc4ODI4NTIyMDcxLWM5NDA0ZTE4Njg5YjRjYWZkMTI5MzQwNDY3YzBjMzE1YzdjOGM5ZjI1NDNiM2JmNzI2YjM5ODE5OTRiNTEyOWE) on the README is not working.

Is there a Slack workspace where the project community gathers? If not, we should remove the Slack badge from the README file.

**Comment by johanbrandhorst** [comment]
Thanks for creating this issue! We have a #grpc-middleware channel on Gophers Slack. Unfortunately invite links to the Gophers Slack sometimes tend to expire, so I think we should probably just remove it from the README and add a note about joining the channel manually. Would you be willing to contribute this change?
