### ISSUE TITLE
[grpc_recovery] Panic in goroutine

### ISSUE THREAD

**Issue by koteesy** [grpc-ecosystem/go-grpc-middleware#441]
Can i handle panic in goroutine with grpc_recovery, or i need manual add recover functions to my goroutines?

**Comment by johanbrandhorst** [comment]
grpc_recovery recovers panics in the goroutine in which the gRPC handler is running. It does not handle goroutines spawned by the handler.

**Comment by miparnisari** [comment]
@johanbrandhorst so what is the alternative? The only workaround that i know is to use https://pkg.go.dev/github.com/sourcegraph/conc/panics#Catcher, but isn't there something more native to Go?

**Comment by johanbrandhorst** [comment]
In general, the way to recover panics in Go is to add a `recover` into a `defer` at the top of the goroutine when spawning it:
```go
func someFunc() {
    var s *string
    go func() {
        defer func() {
            p := recover()
            fmt.Println("paniced!", p)
        }()
        *s
    }()
}
```
See https://go.dev/blog/defer-panic-and-recover
