### ISSUE TITLE
CUE-based validator?

### ISSUE THREAD

**Issue by sashabaranov** [grpc-ecosystem/go-grpc-middleware#444]
[CUE language](https://cuelang.org/) for data validation has been gaining some momentum recently. It claims to have protobuf [integration](https://cuelang.org/docs/integrations/protobuf/) similar to what grpc_validator is doing.

I'm wondering if it would make sense to bring CUE-based data validation in gRPC middleware?

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue. How would that actually work? Do you have a concrete proposal that we can action? I think you'd need some sort of annotation in the protobuf files for the validation logic, right?

**Comment by bwplotka** [comment]
No response back, so closing, we can always reopen, thanks! (:
