### ISSUE TITLE
verbosity **IS NOT** about logging level

### ISSUE THREAD

**Issue by fxrlv** [grpc-ecosystem/go-grpc-middleware#451]
verbosity **IS NOT** about logging level
`grpclog` package logs error by calling method `(*zapGrpcLoggerV2).Error*`
verbosity controls how much details we log, **NOT** level
could you please revert this pull request?

_Originally posted by @fxrlv in https://github.com/grpc-ecosystem/go-grpc-middleware/issues/366#issuecomment-900301726_

**Comment by central182** [comment]
+1

The following is the default implementation of the `grpclog.LoggerV2` interface and it's clear that the intention is to check
_whether the verbosity of the current log (`l`) is within (`<=`) the specified threshold (`g.v`)_.
https://github.com/grpc/grpc-go/blob/41e044e1c82fcf6a5801d6cbd7ecf952505eecb1/grpclog/loggerv2.go#L199-L201

It also feels more intuitive that someone setting the threshold to level 0 (not verbose at all) doesn't want to see logs of level 2 (a bit verbose), while someone setting the threshold to level 99 (very verbose) definitely wants to see everything including logs of level 2.
> The verbosity level 99 is mentioned at https://github.com/grpc/grpc-go#how-to-turn-on-logging.

**Comment by johanbrandhorst** [comment]
Fixed in #452
