### ISSUE TITLE
[ctxzap] Add method to maybe extract logger from context

### ISSUE THREAD

**Issue by slnt** [grpc-ecosystem/go-grpc-middleware#467]
I am writing some database logging middleware that I would like tointeract with the request scoped logger. I don't expect that this middleware will _always_ be used in a GRPC service context alongside `grpc_zap` and `ctxzap`, so I'd like for it to be able to fall back to some default logger when necessary. 

There isn't a clear way to do this right now, since `nullLogger` is unexported.

To support this use case I'd like to propose adding one of:
```go
func IsNullLogger(l *zap.Logger) bool {
	return l == nullLogger
}
```
or
```go
// Extract takes the call-scoped Logger from grpc_zap middleware.
//
// It always returns a Logger that has all the grpc_ctxtags updated.
func Extract(ctx context.Context) *zap.Logger {
	l, ok := MaybeExtract(ctx)
	if !ok {
		return nullLogger
	}
	return l
}

// Extract takes the call-scoped Logger from grpc_zap middleware, if one exists, otherwise
// returns nil and false.
//
// It always returns a Logger that has all the grpc_ctxtags updated.
func MaybeExtract(ctx context.Context) (*zap.Logger, bool) {
	l, ok := ctx.Value(ctxMarkerKey).(*ctxLogger)
	if !ok || l == nil {
		return nil, false
	}

	// Add grpc_ctxtags tags metadata until now.
	fields := TagsToFields(ctx)
	// Add zap fields added until now.
	fields = append(fields, l.fields...)
	return l.logger.With(fields...), true
}
```

**Comment by bwplotka** [comment]
Great idea, but not sure why it has to be hosted in go-grpc-middlewares. The `v2` version has [`logging.ExtractFields`](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/logging/logging.go#L150) that should allow you to create your own context logger. Closing, unless you think that's not enough, we can reopen (:
