### ISSUE TITLE
Noisy Transport Closing Log again on v1.3.0

### ISSUE THREAD

**Issue by seiichi1101** [grpc-ecosystem/go-grpc-middleware#468]
Go Version: 1.17

As mentioned this issue [grpc/grpc-go #2901](https://github.com/grpc/grpc-go/issues/2901), transport closing message is logged everytime on v1.3.0.
This seems to be resolved #221, but it's occurring again on v1.3.0 even though I am using `ReplaceGrpcLoggerV2`.

I run a gRPC server like this:

```go
...
	zapLogger, err := zap.NewDevelopment()
	grpcZap.ReplaceGrpcLoggerV2(zapLogger)

	s := grpc.NewServer(
		grpc.UnaryInterceptor(
			grpcZap.UnaryServerInterceptor(zapLogger),
		),
	)
```

On v1.3.0, I see log like this:

`[transport]transport: loopyWriter.run returning. connection error: desc = "transport is closing" {"system": "grpc", "grpc_log": true}`

However, I don't see the above log on v1.2.2.

Here is the code I tried.
- [go-grpc-middleware-v1.2.2](https://github.com/seiichi1101/test-ReplaceGrpcLoggerV2/tree/go-grpc-middleware-v1.2.2)
- [go-grpc-middleware-v1.3.0](https://github.com/seiichi1101/test-ReplaceGrpcLoggerV2/tree/go-grpc-middleware-v1.3.0)

**Comment by sashayakovtseva** [comment]
They've fixed this in https://github.com/grpc-ecosystem/go-grpc-middleware/pull/452/files

I am facing this issue two. Will update to master instead of v1.3.0, but waiting for release tag.

**Comment by bwplotka** [comment]
Not sure if this is still relevant for `v2`, closing for now, feel free to reopen.
