### ISSUE TITLE
grpc_retry: why linear backoff and not exponential

### ISSUE THREAD

**Issue by aybabtme** [grpc-ecosystem/go-grpc-middleware#47]
ohai!

Just wanted to know why the backoff strategy used here was linear, versus exponential? Was it an omission, a lack of opinion or a choice made on purpose?

**Comment by mwitkow** [comment]
Hey,

I wanted to implement exponential backoff, but the flight I was in wasn't long enough. And for most gRPC errors we encounter (e.g. connection reset which signifies `Unavailable`) a simple linear is enough.

Happy to accept PRs though! :)

**Comment by fengzixu** [comment]
Is this issue is handling by others?  If not, I would like to take that.

**Comment by chimeworld** [comment]
I'd like to work on this if it's still needed.

**Comment by johanbrandhorst** [comment]
This is already supported.
