### ISSUE TITLE
Using ctxzap shorthand helper functions liberally

### ISSUE THREAD

**Issue by ianthpun** [grpc-ecosystem/go-grpc-middleware#470]
Recently I noticed there was a feature merged with some shorthands on how to use the lgoger from context here https://github.com/grpc-ecosystem/go-grpc-middleware/issues/407.

My take on the feature would be able to do something like

```go
func foo(ctx context.Context, ...) (...) {
       ctxzap.AddFields(ctx, 
       zap.String("one", one),
       zap.String("two", two),
       )

	ctxzap.Debug(ctx, "we've at step 1")
	...
        ...
	if err := bar(...); err != nil {
		ctxzap.Extract(ctx).Error("bar failed", zap.Error(err))
	}
	...
	...
       ctxzap.AddFields(ctx, 
       zap.String("three", three),
       zap.String("four", four),
       )
	...
	...
	ctxzap.Debug(ctx, "we're at step 2")
	...
}
```

which is fantastic. However, the docs currently say the `Extract` is an expensive call and should only be called once per handler, noted here https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/ctxzap#pkg-overview

![image](https://user-images.githubusercontent.com/6364887/141168470-1bd7d4fd-1d5a-423e-aefb-f6ef4b2014bc.png)

the helper functions `[Debug,Info,WarnError]` all run `Extract` in the implementation, so this would techincally run itself each time we need to do a log. 

Any suggestions?

**Comment by johanbrandhorst** [comment]
Yeah, that's a good catch. We may want to add that to the doc string of each of these new methods. I'm not sure what you're asking for exactly?

**Comment by ianthpun** [comment]
@johanbrandhorst I am more asking that, if `Extract` calls are really meant to be called once, whats the best practice of  logging while also adding fields to the logger in the context? If we run `ctxzap.Extract(ctx)` in the beginning of the handler and use that logger along the function, i will not have any of the fields added should we use `ctxzap.AddFields` between the calls, since `ctxzap.AddFields` adds the fields into the ctx logger, while the extracted logger called by `ctxzap.Extract` previously doesn't seem to have those fields

**Comment by johanbrandhorst** [comment]
I see. I don't know if there's any way to work around that. It seems to me you either:
* Extract the logger from the context once, and add the fields you want to any log calls _and_ into the context explicitly.
* Take the performance hit and run the convenience functions. Small iterations are not particularly expensive, though of course you should avoid logging things in a busy loop if you can.
Does that make sense?

**Comment by ianthpun** [comment]
@johanbrandhorst yes that does, thanks!

**Comment by johanbrandhorst** [comment]
Thanks for your response, I'll close this issue for now. Feel free to reopen if there's still something unclear.
