### ISSUE TITLE
Support for klog as logging middleware

### ISSUE THREAD

**Issue by alok87** [grpc-ecosystem/go-grpc-middleware#473]
We use github.com/kubernetes/klog extensively in many go projects as the logging library. 

Possible to get it in here as a middleware. Would love to add support if it is possible.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! We're happy to accept this contribution, but consider making it against the v2 branch as we plan to put new work into that branch exclusively.

**Comment by alok87** [comment]
Hey! Great I can add the support. Can you give some reference PR for it and any help on how to go about it will help me do this quick.

**Comment by johanbrandhorst** [comment]
You could check out the `zap` implementation for inspiration: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/providers/zap/logger.go.
