### ISSUE TITLE
v2: Please provide (port) grpc_logsettable.SettableLoggerV2  in go-grpc-middleware/v2

### ISSUE THREAD

**Issue by pavankrish123** [grpc-ecosystem/go-grpc-middleware#479]
Unfortunately v2 doesn't have [SettableLoggerV2](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/logging/settable@v1.3.0) nor has APIs for setting global gRPC logger, as a matter of fact. Only interceptor logs are available on the branch which will not produce framework level logs.

We rely on [SettableLoggerV2](https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/logging/settable@v1.3.0) for setting global grpc logger to zap logger and reset it back as needed. 

Please let me know if you need any further information.

**Comment by pavankrish123** [comment]
I was doing some research and found this comment https://github.com/grpc-ecosystem/go-grpc-middleware/pull/402#issue-831821664. 

Is setting grpc logger via grpc.SetLoggerV2() not something we do not want in v2 at all? Can you please confirm

**Comment by johanbrandhorst** [comment]
I would have to defer to @bwplotka who implemented most of the logging changes 😁

**Comment by bwplotka** [comment]
I am failing to understand what global grpc Logger has to do with interceptors (even logging interceptor) 🤔 

Do you mind giving us TL;DR on how this repo (on `v2` branch) is limiting you on using https://pkg.go.dev/google.golang.org/grpc/grpclog#SetLoggerV2 in your code? Thanks 🤗

**Comment by bwplotka** [comment]
Closing for now, since we didn't hear from you - we can always open, thanks! (:
