### ISSUE TITLE
Update deprecated github.com/golang/protobuf dependency

### ISSUE THREAD

**Issue by Merteg** [grpc-ecosystem/go-grpc-middleware#480]
Go mod marks github.com/golang/protobuf as deprecated. Do you have any plan of updating this to google.golang.org/protobuf

**Comment by johanbrandhorst** [comment]
This is part of our plan for the v2 release, yes! You can use it today from the v2 branch: `go get github.com/grpc-ecosystem/go-grpc-middlewar@v2`
