### ISSUE TITLE
Open Tracing Specific hide GRPC input message

### ISSUE THREAD

**Issue by xantabdoc** [grpc-ecosystem/go-grpc-middleware#481]
i want to log all user input data with open tracing, but want to protect sensitive data too e.g (password, otp) i don't know if it has available feature to hide it.

**Comment by xantabdoc** [comment]
@johanbrandhorst i think https://blog.golang.org/protobuf-apiv2 removing the variable value and i can't use the data after using redacted on middleware 
😿 
> I don't know if we have anything built-in to protect such fields, but if you're using Go you could look at the example in https://blog.golang.org/protobuf-apiv2 maybe?

**Comment by johanbrandhorst** [comment]
Well you don't have to unset it, you can use it to modify the logic of your printer maybe?

**Comment by xantabdoc** [comment]
thanks for helping.
