### ISSUE TITLE
Make use of an Logger interface instead of logrus

### ISSUE THREAD

**Issue by fabioshub** [grpc-ecosystem/go-grpc-middleware#484]
Some method, like the `UnaryServerInterceptor` expect specific Logrus implementations in order to work. It would be handier, if these methods don't rely on Logrus, but on an interface which holds the same methods as the logrus one. That way we can replace the Logrus with a different log implementation. 

Example: 
![image](https://user-images.githubusercontent.com/36661261/155338229-cd5300ad-ec3b-480e-b790-c2c424b1fcf1.png)

**Comment by bwplotka** [comment]
This is fixed in `v2` (https://github.com/grpc-ecosystem/go-grpc-middleware/tree/v2/interceptors/logging). Enjoy. (:
