### ISSUE TITLE
Retry Middleware not Honored

### ISSUE THREAD

**Issue by halspang** [grpc-ecosystem/go-grpc-middleware#485]
*Copied from grpc-go repo*

### What version of gRPC are you using?
`google.golang.org/grpc v1.40.0`
`github.com/grpc-ecosystem/go-grpc-middleware v1.2.2`

### What version of Go are you using (`go version`)?
1.17.1

### What operating system (Linux, Windows, …) and version?
Mac 12.2.1

### What did you do?
If possible, provide a recipe for reproducing the error.

This happens during a gRPC proxying flow inside of [dapr](http://github.com/dapr/dapr).

Adding the `WithMax/WithPerRetryTimeout` to a `ClientStream` did not result in any retries. We added them as CallOptions here: https://github.com/dapr/dapr/blob/master/pkg/grpc/proxy/handler.go#L75

This called into a .NET gRPC app which threw a:

```csharp
throw new RpcException(new Status(StatusCode.ResourceExhausted, "Resource exhausted"));
```

Here's the ClientStream initialization:

```go
clientStream, err := grpc.NewClientStream(clientCtx, clientStreamDescForProxying, backendConn, fullMethodName, grpc.CallContentSubtype((&codec.Proxy{}).Name()), grpc_retry.WithMax(5), grpc_retry.WithPerRetryTimeout(time.Second), grpc_retry.WithCodes(codes.ResourceExhausted))
```

### What did you expect to see?
The request should have retried up to the max set (5) and with a timeout of 1 second between each call.

### What did you see instead?
No retries fired.

Original issue: https://github.com/grpc/grpc-go/issues/5208

**Comment by johanbrandhorst** [comment]
What calls did you make to trigger this? It won't work with streaming calls.

**Comment by halspang** [comment]
I was trying to use it in a gRPC proxying call. Since we're proxying it, we don't know which side will end the request first and it becomes a streaming call. Based on what you're saying, it sounds like it's not going to work. You can see how we're doing streaming here https://github.com/dapr/dapr/blob/master/pkg/grpc/proxy/handler.go#L75.

Given that, do you have any pointers for this? I've also just retried the failed call but since it's mid stream I get a lot of `IncompleteMessage` errors. Also feel free to close this issue if this is expected :)

**Comment by johanbrandhorst** [comment]
I'm not sure if there's anything obvious that you can do to a streaming call - with a unary call it's natural to just retry, but with a streaming call you might have sent some messages successfully, received one error and then continued to send messages happily. What sort of automatic behavior do you expect here? In any case, I doubt there's anything we can do in this repository to fix it. Sorry to disappoint!
