### ISSUE TITLE
loggingClientStream log wrong

### ISSUE THREAD

**Issue by mochen302** [grpc-ecosystem/go-grpc-middleware#486]
Hi,
In struct logging/zap/payload_interceptors.loggingClientStream and loggingServerStream,
the log is so strange!
logging**Client**Stream.SendMsg logs -> "grpc.request.content" with "**server request** payload logged ..." 
logging**Client**Stream.RecvMsg logs -> "grpc.response.content" with "**server request** payload logged ..." 
loggingServerStream.**Send**Msg logs -> "grpc.**response**.content"
loggingServerStream.**Recv**Msg logs -> "grpc.**request**.content"

**Comment by bwplotka** [comment]
Sorry, this is bit cryptic issue. 

Please make sure to use `v2` branch (soon official) and report back if issues persist with more information on what interceptors you actually use and how. Thanks!
