### ISSUE TITLE
implement an interceptor for zerolog

### ISSUE THREAD

**Issue by KaymeKaydex** [grpc-ecosystem/go-grpc-middleware#488]
https://github.com/rs/zerolog

**Comment by nashikb** [comment]
See v2.

**Comment by KaymeKaydex** [comment]
> See v2.

Where?

**Comment by xdorro** [comment]
I'm looking forward to the grpc-middleware to support zerolog soon

**Comment by xdorro** [comment]
@nashikb  when will v2 be released?

**Comment by nashikb** [comment]
I'm not sure what the project's plans are in terms of timing @johanbrandhorst, but FWIW I've been using v2.0.0-rc.2 (and rc1) in production since zerolog was merged with no issues.

**Comment by johanbrandhorst** [comment]
I think there are still some things that we want to do before tagging a stable v2, but @bwplotka will know best.

**Comment by KaymeKaydex** [comment]
if I have time, I will try to support this logger

**Comment by BorzdeG** [comment]
I use this repository: [github.com/pereslava/grpc_zerolog](https://github.com/pereslava/grpc_zerolog)

**Comment by bwplotka** [comment]
Done on [v2](https://github.com/grpc-ecosystem/go-grpc-middleware/tree/v2/providers/zerolog) and we are just about to release v2.0.0
