### ISSUE TITLE
In auth interceptor I want to ignore login method, but I don't know how to do it

### ISSUE THREAD

**Issue by Pluto-yubin** [grpc-ecosystem/go-grpc-middleware#489]
I don't know how to get method name in authFunc because I cant get` info *grpc.UnaryServerInfo,` I found I can implement `AuthFuncOverride` method in info.Server, but I still need to pass a useless authFunc to `grpc_auth.UnaryServerInterceptor`, it seems to make no sense, I want to know whether I can use another way to ignore methods in specified name in `grpc_auth.UnaryServerInterceptor`

**Comment by esenmx** [comment]
Don't use `AuthFuncOverride`, it's very simple, you need to implement interceptor manually.

A related issue and your answer is here: https://github.com/grpc-ecosystem/go-grpc-middleware/issues/213

**Comment by Pluto-yubin** [comment]
> Don't use `AuthFuncOverride`, it's very simple, you need to implement interceptor manually.
> 
> A related issue and your answer is here: #213

I got it, thank you
