### ISSUE TITLE
[grpc_validator] Accept log as argument in the interceptor and log on failure

### ISSUE THREAD

**Issue by liadmord** [grpc-ecosystem/go-grpc-middleware#494]

**Comment by bwplotka** [comment]
Fair request, help wanted, PR welcome (to `v2` branch).

**Comment by rohanraj7316** [comment]
@bwplotka do you have any preference here regarding the logging `prefix + error msg` or `error msg`?

**Comment by bwplotka** [comment]
No strong opinion on that, but we need to improve validator API before v2, so if you could help with that, it would be fabulous 😱 (mentioned [here](https://github.com/grpc-ecosystem/go-grpc-middleware/pull/544/files#r1143940687))

**Comment by bwplotka** [comment]
Fixed in https://github.com/grpc-ecosystem/go-grpc-middleware/pull/544
