### ISSUE TITLE
Exposing the Request to Streaming Server Interceptors

### ISSUE THREAD

**Issue by SSSOCPaulCote** [grpc-ecosystem/go-grpc-middleware#504]
For unary interceptors, the `req interface{}` is exposed to validate any request parameters. It would be very helpful if the request interface was also exposed for streaming interceptors, but for my specific use case, the streaming server interceptor.

I read somewhere that I could implement the `grpc.ServerStream` interface and grab the request from `RecvMsg(m interface{})` function. I tried that and when I would `switch request := m.(type){}` and print out the value of the type asserted request, it would always be blank. I've had to resort to duplicating some code and moving authentication to the actual implementation of the streaming RPC function which feels wrong considering I have auth middleware for unary commands.

I'm open to alternatives, I probably missed something and this change isn't needed but figured I'd ask.

**Comment by SSSOCPaulCote** [comment]
To be clear, the reason why I don't want to do this in the actual function implementation is because I extract a specific parameter from the request, insert it into the context and pass that along to my auth function. Basically, I'm creating an API authentication system where credentials can be valid for specific commands with specific arguments. Which is why doing this in middleware is ideal.

**Comment by johanbrandhorst** [comment]
Hi, I believe this isn't something that we can control in this repo, it's dictated by the interceptor interface exposed by the grpc-go library. Am I misunderstanding?

**Comment by bwplotka** [comment]
I think you could try using our v2 interceptor with reporter interface https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/reporter.go#L90, let us know if this work!

**Comment by SSSOCPaulCote** [comment]
This looks really interesting. Essentially, I had to move my authentication for any streaming endpoints to the RPC function implementation as opposed to doing it in middleware. With these changes, it seems I may be able to implement something using the `ServerReportable` interface.

**Comment by bwplotka** [comment]
Sounds like this is solved, feel free to visit our Slack channel or we can reopen this issue, thanks!
