### ISSUE TITLE
[ERROR]: ambiguous import in auth/auth_test.go

### ISSUE THREAD

**Issue by panjf2000** [grpc-ecosystem/go-grpc-middleware#515]
I ran `go mod tidy` and get this output: 

```powershell
	github.com/grpc-ecosystem/go-grpc-middleware/auth tested by
	github.com/grpc-ecosystem/go-grpc-middleware/auth.test imports
	google.golang.org/grpc/credentials/oauth imports
	golang.org/x/oauth2/google imports
	cloud.google.com/go/compute/metadata: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
	cloud.google.com/go v0.65.0 (/Users/andypan/dev/go/pkg/mod/cloud.google.com/go@v0.65.0/compute/metadata)
	cloud.google.com/go/compute v1.7.0 (/Users/andypan/dev/go/pkg/mod/cloud.google.com/go/compute@v1.7.0/metadata)
```

Related issue: #377

**Comment by johanbrandhorst** [comment]
Which branch was this? I can run this just fine on `master`. Do you need to update one of your dependencies?

**Comment by panjf2000** [comment]
> Which branch was this? I can run this just fine on `master`. Do you need to update one of your dependencies?

v1.3.0, and it can be resolved by adding `eplace cloud.google.com/go v0.65.0 => cloud.google.com/go/compute v1.7.0
` to go.mod

**Comment by johanbrandhorst** [comment]
Thanks for the workaround. Do you think we need to update our dependency?

**Comment by panjf2000** [comment]
Hi @johanbrandhorst , sorry for the delay, it's been a busy month. The ambiguous import is caused by [oauth2](https://github.com/golang/oauth2), and `cloud.google.com/go v0.65.0` in go.mod of that repo has been replaced to `cloud.google.com/go/compute v1.7.0`, see [this commit](https://github.com/golang/oauth2/commit/2104d58473e0869996f17ef05fb7e0cc9bd19312),  thus the solution for this issue is to bump up the dependencies of go-grpc-middleware.

I'd love to help open a PR fixing this issue, but it got stuck with one problem: conflict registration of protobuf: panic: proto: message mwitkow.testproto.PingRequest is already registered (after upgrading grpc from 1.29 to 1.50), when running `go test`, caused by the same `mwitkow.testproto.PingRequest` in test.proto and fields.proto, I've tried to rename the package name of fields.proto and run `make fields_go`, but instead of a re-generated *.pb.go file, I got: fields.proto:6:1: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.

Could you help me with this? how do I re-compile the fields.pb.go?

**Comment by johanbrandhorst** [comment]
Yaeh I don't think it's worth trying to fix the dependencies on `master`, give `v2` a try instead.

**Comment by nickzelei** [comment]
Tried bumping to the `v2` branch but the problem persists there.
I think it's because the `golang.org/x/oauth2` version in the v2 branch is still pretty old. Sitting at `golang.org/x/oauth2 v0.0.0-20210413134643-5e61552d6c78`
Bumping it to `v0.3.0` will probably fix the issue.

**Comment by johanbrandhorst** [comment]
Sounds like an easy fix :)

**Comment by bwplotka** [comment]
oauth2 is now at v0.4.0
