### ISSUE TITLE
[Feature] [grpc_retry] Support user defined retry option

### ISSUE THREAD

**Issue by bigsheeper** [grpc-ecosystem/go-grpc-middleware#516]
Currently retry intercepor only supports:

```go
func WithMax(maxRetries uint) CallOption
func WithBackoff(bf BackoffFunc) CallOption
func WithBackoffContext(bf BackoffFuncContext) CallOption
func WithCodes(retryCodes ...codes.Code) CallOption
func WithPerRetryTimeout(timeout time.Duration) CallOption
```

In some cases, we need to retry on some special cases when specific error returned from server, like:
```go
if callOpts.udf != nil && callOpts.udf() {
    continue
}
if !isRetriable(lastErr, callOpts) {
    return lastErr
}
```

and the udf would be like:
```go
grpc_retry.WithUDF(func(reply interface{}) bool {
    specialError := errors.New("special error")
    if err, ok := reply.(error); ok && errors.Is(err, specialError) {
	return true
    }
    return false
})
```

**Comment by johanbrandhorst** [comment]
I'm not convinced there is enough need for this. Is this not a very slippery slope of all kinds of new feature requests? At some point, as a user, you just define your own interceptor.

**Comment by bwplotka** [comment]
Thanks for this proposal. What's UDF?

If you mean `WithCodes` being not specific enough, and we need to add `WithRetryOnSpecificError`, it's not too wild addition. I think I would welcome such small PR.

**Comment by musafir-V** [comment]
@bwplotka are we still looking for PRs for this?

**Comment by bwplotka** [comment]
Only if it's needed. We don't want to maintain code which noone uses.

**Comment by bwplotka** [comment]
So let's wait for the author. Will close for now, we can reopen if still needed, some time has passed.
