### ISSUE TITLE
Update v2 readme for how to use `logging.ExtractFields`

### ISSUE THREAD

**Issue by Hongbo-Miao** [grpc-ecosystem/go-grpc-middleware#521]
I saw [v2 changelog](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/CHANGELOG.md#changed) says:

> `tags` removed. Use `logging.ExtractFields` to read logging fields from logging interceptor for your local request logger. Use `logging.InjectFields` to inject custom fields to logging interceptor to client context or interceptor before logging interceptor.

In the [v2 readme](https://github.com/grpc-ecosystem/go-grpc-middleware/tree/v2#middleware) demo, it still uses old `tags`:

```go
import "github.com/grpc-ecosystem/go-grpc-middleware/v2"

myServer := grpc.NewServer(
    grpc.ChainStreamInterceptor(
        tags.StreamServerInterceptor(),
        opentracing.StreamServerInterceptor(),
        prometheus.StreamServerInterceptor,
        zap.StreamServerInterceptor(zapLogger),
        auth.StreamServerInterceptor(myAuthFunction),
        recovery.StreamServerInterceptor(),
    ),
    grpc.ChainUnaryInterceptor(
        tags.UnaryServerInterceptor(),
        opentracing.UnaryServerInterceptor(),
        prometheus.UnaryServerInterceptor,
        zap.UnaryServerInterceptor(zapLogger),
        auth.UnaryServerInterceptor(myAuthFunction),
        recovery.UnaryServerInterceptor(),
    ),
)
```

It would be great to update readme for how to use `logging.ExtractFields`. Thanks! 😃

**Comment by johanbrandhorst** [comment]
Great spot. Would you be willing to update this? Thanks!

**Comment by Hongbo-Miao** [comment]
Hi @johanbrandhorst I wish I could. 🥲
I actually didn't fully understand how to use `logging.ExtractFields` which is why I created this ticket.

**Comment by kon3m** [comment]
Even I'm trying to understand how the new implementation works. It would be great if the authors update the documentation @johanbrandhorst @bwplotka . I wanted to know how does the current implementation replace tags.

**Comment by aimuz** [comment]
https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/interceptors/auth/examples_test.go#L41

 I hope this can help you

**Comment by bwplotka** [comment]
Thx! So the way it should be used is by creating your own interceptor that InjectFields. However this might a bit challenging for those new to interceptors (users that this library aim for), so I am experimenting with simple "WithExtraFieldsFromCtx" option in logging interceptor and making InjectFields and ExtractFields private for now.

**Comment by bwplotka** [comment]
Closing as README was updated. Expect more examples very soon!
