### ISSUE TITLE
Exporting full methods

### ISSUE THREAD

**Issue by KenxinKun** [grpc-ecosystem/go-grpc-middleware#524]
Hi, we have a use case using grpc interceptors to check for permissions/authorization server-side when calling a particular gRPC endpoint. We're doing something like:

```
func NewPermissionsInterceptor(permission PermissionChecker) grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
		if !permission.HasPermission(ctx, info.FullMethod) {
			return nil, errors.New("permissions denied")
		}

		return handler(ctx, req)
	}
}
```

where the `.HasPermission(...)` method contains a hard coded copy of the methods used by the `protoc-gen-gofullmethods` command.

Would it be possible to allow the protoc command to export the method strings directly, so that we can access them? (they're currently written twice for client and server respectively, but not exposed as a package exported constant).

I believe this might be useful to others trying to make similar middleware / interceptors. If this is something you'd like to support I'd be happy to fork and contribute the development time with a PR :)

**Comment by johanbrandhorst** [comment]
Hi, thanks for the issue. I'm a little confused about this ask being created in this repo. We don't support any generators in this repo, nor do we parse the protobuf files which have access to this information. Did you mean to raise this issue against https://github.com/golang/protobuf/issues?

**Comment by KenxinKun** [comment]
My bad @johanbrandhorst I thought you were the publishers of the protoc-gen-go-grpc plugin!
