### ISSUE TITLE
grpc retry is not working between two golang services.

### ISSUE THREAD

**Issue by jchaur** [grpc-ecosystem/go-grpc-middleware#525]
I have implemented grpc retry between two golang services. But retries are not working.  To test this i have stopped server manually and client is trying to make grpc call. But getting error immediately , It should have tried for some time before throwing error.

Any help will be highly appreciated

var retry = []grpc_retry.CallOption{
	grpc_retry.WithBackoff(grpc_retry.BackoffLinear(50)),
	grpc_retry.WithCodes(codes.Aborted, codes.Canceled, codes.DataLoss, codes.DeadlineExceeded, codes.FailedPrecondition, codes.Internal, codes.NotFound, codes.ResourceExhausted, codes.PermissionDenied, codes.OutOfRange, codes.Unauthenticated, codes.Unavailable, codes.Unknown),
	grpc_retry.WithMax(4),
}

grpc.Dial(*addr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.FailOnNonTempDialError(false),
		grpc.WithBlock(),
		grpc.WithUnaryInterceptor(grpc_retry.UnaryClientInterceptor(retry...)),
	)
	
**Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.5.173:9090: connect: connection refused"**

**Comment by johanbrandhorst** [comment]
The retry interceptor is for single RPC call failures, not dial failures. You will need a successful initial dial before the retry interceptor will work.

**Comment by jchaur** [comment]
@johanbrandhorst  Thanks for your Reply. I have also tested by explicitly failing RPC  like below but still it is not working. 
Checked via sample separately , there retry is happening with same configuration. Please help if I am missing something. Also how can i debug or simulate this .

**return status.Errorf(codes.Unavailable, "maybeFailRequest: failing it")**

Thanks

**Comment by johanbrandhorst** [comment]
I'm a little confused still. Could you provide a more complete example? I would expect it to retry calls that returned this error.
