### ISSUE TITLE
Support extra labels for gRPC prometheus

### ISSUE THREAD

**Issue by xin-tsla** [grpc-ecosystem/go-grpc-middleware#532]
Hi Team,
We have some use case need to know which source sends gRPC requests. Right now, the gRPC prometheus metrics do not have customized extra labels except: `grpc_service`, `grpc_method`, `grpc_type` and `grpc_code`.
Wondering does it make sense to support extra labels?
If so, I could prepare a PR for it.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I generally prefer to keep the interceptors simple and less configurable, if you need something added you can always create your own interceptor based on the ones we have. I don't know if this is exactly what you need, but it looks like the v2 branch lets you specify labels: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/v2/providers/openmetrics/options.go#L32.

**Comment by xin-tsla** [comment]
@johanbrandhorst , thanks for the quick relay! Yes, I looked at the constsLabels, it seems it could not be used as variable labels.

**Comment by johanbrandhorst** [comment]
I would prefer not to add this functionality into the library. Please copy the relevant parts to your own interceptor for this functionality.

**Comment by xin-tsla** [comment]
@johanbrandhorst , got it. Understood.

**Comment by xin-tsla** [comment]
Thanks for replying! 👍 Closing the issue now.
