### ISSUE TITLE
Grpc client Wrap Dial function 

### ISSUE THREAD

**Issue by abhi9560** [grpc-ecosystem/go-grpc-middleware#536]
When i Wrap grpc.Dial function with own function it is getting error 

goroutine 1 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).updateClientConnState
	/root/go/src/google.golang.org/grpc/balancer_conn_wrappers.go:158 
google.golang.org/grpc.(*ClientConn).updateResolverState
	/root/go/src/google.golang.org/grpc/clientconn.go:678 
google.golang.org/grpc.(*ccResolverWrapper).UpdateState
	/root/go/src/google.golang.org/grpc/resolver_conn_wrapper.go:102 
google.golang.org/grpc/internal/resolver/passthrough.(*passthroughResolver).start
	/root/go/src/google.golang.org/grpc/internal/resolver/passthrough/passthrough.go:55 

####my code :- 
func WrapClient(target string, opts ...grpc.DialOption)(*grpc.ClientConn, error){
        
      	opts = append(opts, grpc.WithUnaryInterceptor(NewUnaryClientInterceptor()))
        conn, err := grpc.Dial(target,opts...)
        if err != {
        	log.Fatalf("did not connect : %v",err)
        }
        return conn,err
}

**Comment by johanbrandhorst** [comment]
This isn't the right place to raise an issue about a problem with the Go gRPC library, please try https://github.com/grpc/grpc-go.
