### ISSUE TITLE
Question about cancelling stream methods

### ISSUE THREAD

**Issue by phonkee** [grpc-ecosystem/go-grpc-middleware#56]
When I have custom code in stream interceptor right after calling `handler(srv, wrapped)`. When client cancels context, the code after the handler is not executed.
Is this grpc error, or middeware error?

**Comment by mwitkow** [comment]
Sorry, can you please clarify:
a) are you talking about a server stream interceptor or a client stream interceptor
b) are you tlaking about any of the interceptors here?

In general if a context is cancelled, the `handler(srv, wrapped)` will return a context.Cancelled. If an interceptor wants to do something else *without relying on context* (e.g. log an error) it can do so.

**Comment by phonkee** [comment]
I am talking about server stream interceptor. 
Then when I make a call with client, and cancel client context, the code in server stream interceptor that is after `handler(srv, wrapped)` is not reached.

**Comment by mwitkow** [comment]
Can you give a code example? Do you also wrap the Stream obhect?

**Comment by phonkee** [comment]
Sure,

Let's have some simple example

	func StreamServerInterceptor() grpc.StreamServerInterceptor {
		return func(srv interface{}, stream grpc.ServerStream, info *grpc.StreamServerInfo, handler grpc.StreamHandler) (err error) {
	
			wrapped := grpc_middleware.WrapServerStream(stream)
			wrapped.WrappedContext = stream.Context()
	
			// call handler
			err = handler(srv, wrapped)
			println("grpc request")
	
			return
		}
	}

I have simplified my code to this example.
Then when I call grpc stream method from client with context that was created with `context.WithCancel`, and I call the cancel method from client, `println("grpc request")` will not be called in the interceptor

**Comment by mwitkow** [comment]
Does it even get into `handler` line? If it is `context.Cancelled`, then it may not even get to the server interceptor lines.

Otherwise this feels more like a grpc-go upstream bug.
