### ISSUE TITLE
validation interceptor in streaming RPCs?

### ISSUE THREAD

**Issue by miparnisari** [grpc-ecosystem/go-grpc-middleware#589]
https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware/validator#StreamServerInterceptor  says

> StreamServerInterceptor returns a new streaming server interceptor that validates incoming messages. The stage at which invalid messages will be rejected with `InvalidArgument` varies based on the type of the RPC. For `ServerStream` (1:m) requests, it will happen before reaching any userspace handlers.

If I put the validation interceptor before all the rest, is there any way to guarantee that validation will be the first thing to happen?

**Go version used**: 1.20

**What happened**:

I have a custom interceptor that, based on input data, attempts to set a header in the response (both unary and streaming). But if the input data is invalid, the streaming endpoint fails with a weird error because my custom interceptor throws an error.

**What you expected to happen**:

Validation should happen before any other interceptor.

**How to reproduce it (as minimally and precisely as possible)**:

1. Pull https://github.com/miparnisari/jaegerGoTest
2. Run `docker-compose up`
3. Run `curl http://localhost:8080/streamed/01G65Z755AFWAKHE12NY0CQ9FH%0A` .

You'll get

```
{"code":13, "message":"invalid header field value for \"store-id-header\"", "details":[]}% 
```

instead of what I expect

```
{"code":3, "message":"invalid StreamedGetStoreRequest.StoreId: value does not match regex pattern \"^[ABCDEFGHJKMNPQRSTVWXYZ0-9]{26}$\"", "details":[]}%
```

**Comment by johanbrandhorst** [comment]
The execution order of interceptors is determined by the way you're invoking the grpc library. in https://github.com/miparnisari/jaegerGoTest/blob/master/main.go#L83 you're calling https://pkg.go.dev/google.golang.org/grpc#WithChainStreamInterceptor. It says that the first in the list is the outermost one in the execution. It seems that you put the validation interceptor before your custom header interceptor, so I would expect it to do the validation first. This isn't the right forum for this sort of debugging, but it seems like you want to figure out why the validator isn't being called. It seems to me like you might want to start by trying to use the latest version of our library. Try replacing https://github.com/miparnisari/jaegerGoTest/blob/master/main.go#LL9C50-L9C50 with
```
	grpc_validator "github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptorsvalidator"
```
That might work? I think you need someone who can give you more direct feedback, and this isn't the right forum for that. Maybe try the [Gophers Slack](https://invite.slack.golangbridge.org/)?

**Comment by miparnisari** [comment]
Thanks for the reply @johanbrandhorst! Unfortunately, updating the library version didn't help :(
