### ISSUE TITLE
When will a V2 be released?

### ISSUE THREAD

**Issue by simon-soderlind** [grpc-ecosystem/go-grpc-middleware#594]
Just wondering when there will be a V2 release? In the [v2.0.0-rc.5](https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/v2.0.0-rc.5) the middle of April was mentioned. Is there a new date in mind?

**Comment by johanbrandhorst** [comment]
CC @bwplotka I believe we were planning on doing this shortly.

**Comment by Setheck** [comment]
Really excited for this!

**Comment by brettmorien** [comment]
Hi folks. Just checking up on this v2 release. Any updates for us?

**Comment by bwplotka** [comment]
Done: https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/v2.0.0 (:
