### ISSUE TITLE
open wiki pages.

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/go-grpc-middleware#63]
I will post some codes there to show the examples.

**Comment by mwitkow** [comment]
I much prefer example code to be provided as a Golang-compilable code, so it can be kept in sync.

Please either provide additional `Example_` test methods a la: https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/auth/examples_test.go

Or we can start a example subdirectory.

**Comment by jinleileiking** [comment]
that needs merge, A little bit bore :(. BUT IS BETTER.
