### ISSUE TITLE
Question, binary file streaming

### ISSUE THREAD

**Issue by bjornl** [grpc-ecosystem/go-grpc-middleware#65]
Hi, I have a question if you know of any existing Go library providing support for file and blob streaming over gRPC?

Example use cases include microservices providing a API for converting media formats (image, audio, video) or microservices providing file compression, text-to-speech, etc.

I found this thread https://github.com/grpc/grpc-go/issues/414 , this seam to be a pretty common need so I figure others must have had dealt with it.

**Comment by mwitkow** [comment]
https://github.com/googleapis/googleapis/blob/master/google/bytestream/bytestream.proto

is a good example of a canonical API for this. Probably worthwhile building a set of reusable tools around it that will provide a `io.Writer` and `io.Reader` around it. But this is outside the scope of this repo.
