### ISSUE TITLE
Ctx_tags to populate both Request & Response Logging

### ISSUE THREAD

**Issue by ds0nt** [grpc-ecosystem/go-grpc-middleware#66]
I like being able to define tags in proto, and have the ctx_tags middleware extract them. This then can be used from request logging interceptors later down the middleware chain.

Can I do this for response logging too? It seems by default the logrus middleware when used with ctx_tags just logs the request. If I add a payload interceptor that is always true, then it logs out the response in grpc.response.content, as a full json struct.

I was hoping it would log like request, and use the opentrace format and populate only the tagged fields.

Any ideas?

This is the sort of logs I'm getting

```json
{"app":"ticket_svc","grpc.code":"OK","grpc.method":"GetTicket","grpc.request.id":"e5179cd4-4c03-41f8-bc07-52d9fcf7bc85","grpc.service":"actourex.core.service.ticket.Command","grpc.time_ms":42,"level":"info","msg":"finished unary call","peer.address":{"IP":"::1","Port":52958,"Zone":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2017-07-05T18:14:10Z"}

# it would be nice if I could figure out how to have this print with keys like: grpc.response.id = blah, grpc.response.some_other_tagged_field = blah2
{"app":"ticket_svc","grpc.response.content":{ ... the full json payload... },"level":"info","msg":"server response payload logged as grpc.request.content field","severity":"INFO","time":"2017-07-05T18:14:10Z"}

```

**Comment by ds0nt** [comment]
I feel like it would need to log both from within, and from outside the ctx_tags middleware

**Comment by ds0nt** [comment]
As in, a middleware before and after ctx_tags in the middleware chain

**Comment by ds0nt** [comment]
Sortof feels like tag extraction should be included as a package in logging middleware

**Comment by jinleileiking** [comment]
You can write a middleware to do this.

**Comment by ds0nt** [comment]
Hey, thanks for the reply.

Yep. Currently building a custom one to work with our stack.

Thanks!

**Comment by mwitkow** [comment]
Yup, the middlewares are fairly composable :) Closing.
