### ISSUE TITLE
[validator] Let me customize the error code

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/go-grpc-middleware#67]
```
				return nil, grpc.Errorf(codes.InvalidArgument, err.Error())
```

I want to not use codes.InvalidArgument =3, so give me a opt to let me choose what errcode to return

**Comment by mwitkow** [comment]
Happy to accept a PR that introduces an option to it.

**Comment by bwplotka** [comment]
This is pretty old and we know have `v2` code with different structure. Let us know if this is still important, we can reopen.
