### ISSUE TITLE
[logging] disable option does not work with request/response fields

### ISSUE THREAD

**Issue by frankgreco** [grpc-ecosystem/go-grpc-middleware#679]
**Go version used**:

`go1.21.3`

**What happened**:

With the following configuration, I do not see these fields ignored.
```
logOpts := []grpc_logging.Option{
  grpc_logging.WithLogOnEvents(
    grpc_logging.StartCall,
    grpc_logging.FinishCall,
    grpc_logging.PayloadReceived,
    grpc_logging.PayloadSent,
  ),
  grpc_logging.WithDisableLoggingFields("grpc.response.content", "grpc.request.content"),
}
```

**What you expected to happen**:

I expect them to be ignored.

**How to reproduce it (as minimally and precisely as possible)**:

Use that above config.

**Comment by johanbrandhorst** [comment]
Hi. You need to use one of the constants as options: https://github.com/grpc-ecosystem/go-grpc-middleware/pull/631/files#diff-8c12c7fac52459b44598f215bb359e03c4ac3678de743b90e4a88c9ad9b03272R42-R47. It isn't a general purpose log disabling option. We could definitely do with some better documentation here. CC @coleenquadros

**Comment by johanbrandhorst** [comment]
Some better docs have been added to this method, hopefully that will avoid confusion around this in the future.

**Comment by johanbrandhorst** [comment]
It's not possible today AFAIK, but maybe it could be added if it makes sense? I often recommend users just fork if they have very specialized needs, but if you think it makes sense as a general purpose option we could consider that too.

**Comment by johanbrandhorst** [comment]
I'd consider it a separate issue, if you don't mind. If we could tie it to the existing option that would be great too.
