### ISSUE TITLE
providers/prometheus v1.0.0 dependent on go-grpc-middleware v2.0.0-rc.3

### ISSUE THREAD

**Issue by marefr** [grpc-ecosystem/go-grpc-middleware#705]
**Go version used**: go version go1.22.1 darwin/arm64

**What happened**:
Installed `github.com/grpc-ecosystem/go-grpc-middleware/providers/prometheus` v1.0.0 and noticed that is dependent on `github.com/grpc-ecosystem/go-grpc-middleware/v2 v2.0.0-rc.3` which seems a bit odd.

**What you expected to happen**:
A prometheus middleware version for the latest `github.com/grpc-ecosystem/go-grpc-middleware/v2`, such as v2.1.0.

**How to reproduce it (as minimally and precisely as possible)**:
Have a look at changes in https://github.com/grafana/grafana-plugin-sdk-go/pull/961.

**Comment by johanbrandhorst** [comment]
Yeah, this seems reasonable to me, was this just an oversight when we released 1.0.0 @bwplotka?

**Comment by bwplotka** [comment]
Correct, help wanted to fix it! Thanks for noticing.

**Comment by marefr** [comment]
I'll open a PR to upgrade prometheus gp.mod. Can you tag/release a new version then?

**Comment by marefr** [comment]
https://github.com/grpc-ecosystem/go-grpc-middleware/pull/706

**Comment by johanbrandhorst** [comment]
I released v1.0.1 of the prometheus provider, hopefully that works :)
