### ISSUE TITLE
[zap]Let me choose the field name.

### ISSUE THREAD

**Issue by jinleileiking** [grpc-ecosystem/go-grpc-middleware#71]
From the code, we can see:

`ServerField = zap.String("span.kind", "server")`

` zap.String("grpc.code", code.String()),`

I use elk, when put log parsed to es, it will fail.

Let me customize the `grpc.code` field, 

for example: use grpc_code

**Comment by mwitkow** [comment]
Can you elaborate on the ES failures? Is it not happy with dots in key names?

**Comment by jinleileiking** [comment]
@mwitkow yes. ES not happy with dots in key names. Es likes: grpc_code

**Comment by jinleileiking** [comment]
@mwitkow and KSQL is not happy with dot. `grpc.code` cannot recongized.

**Comment by mwitkow** [comment]
@devnev @yifanzz 
Can you guys check if this is affecting us, and whether we need to add an option to move to an underscore as a separator instead?
