### ISSUE TITLE
Feature: protovalidate: Add custom ErrorConverter

### ISSUE THREAD

**Issue by khasanovbi** [grpc-ecosystem/go-grpc-middleware#712]
Add ability to customize error text that returned by protovalidate interceptor

**Comment by khasanovbi** [comment]
https://github.com/grpc-ecosystem/go-grpc-middleware/pull/711

**Comment by johanbrandhorst** [comment]
I left a comment on your PR before seeing this issue, sorry. I don't think this is necessary, you can just fork the interceptor if you want to change the behavior.

**Comment by khasanovbi** [comment]
Hi @johanbrandhorst 
I could explain this is necessary for me:
1) This changes allow to customize ugly protovalidate error message to more convenient.
Sample of usage in my project:
```golang
	var targetErr *protovalidate.ValidationError
	if !errors.As(err, &targetErr) {
		return err
	}

	builder := strings.Builder{}
	for i, violation := range targetErr.Violations {
		builder.WriteString(violation.FieldPath)
		builder.WriteString(": ")
		builder.WriteString(violation.Message)

		if i == len(targetErr.Violations)-1 {
			continue
		}

		builder.WriteString("\n")
	}
```
2) This changes could add ability to use `status.WithDetails` and pass field violations in details proto.

**Comment by johanbrandhorst** [comment]
I appreciate that it might be useful to you, but it's very easy to just copy the logic from the interceptors instead of adding more complexity. Please feel free to copy it (as long as you include the license, of course) and make the changes you want.
