### ISSUE TITLE
feat: Add `Context` parameter to custom handler panic recovery intercepter

### ISSUE THREAD

**Issue by afifurrohman-id** [grpc-ecosystem/go-grpc-middleware#724]
**Go version used**:
1.22 linux/amd64

**What happened**:
When i want to use some data from context, or something like trace using OTel it would really useful
```go
recovery.UnaryServerInterceptor(recovery.WithRecoveryHandler(func(ctx context.Context, p any) (err error) { // TODO
})
```
**What you expected to happen**:
I Should easily get context from parameter

**Comment by johanbrandhorst** [comment]
This would be a breaking change, I suggest just forking the relevant interceptor and making the changes you need.
