### ISSUE TITLE
Change Sirupsen imports to sirupsen

### ISSUE THREAD

**Issue by ds0nt** [grpc-ecosystem/go-grpc-middleware#73]
Should probably change the Sirupsen import to the lowercased version. (unfortunately)

https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

**Comment by suprememoocow** [comment]
Revert https://github.com/grpc-ecosystem/go-grpc-middleware/pull/54

**Comment by AlekSi** [comment]
Why revert? I think #54 did the right thing.

**Comment by mwitkow** [comment]
lowercase `sirupsen/logrus` is already in the codebase.
