### ISSUE TITLE
Build fails due to metadata api changes

### ISSUE THREAD

**Issue by joshuarubin** [grpc-ecosystem/go-grpc-middleware#77]
`metadata.NewContext` and `metadata.FromContext` have been removed from the grpc-go repository and now `metautils` fails to build.

[utils/metautils/single_key.go#25](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/util/metautils/single_key.go#L25)

metadata: Remove NewContext and FromContext for gRFC L7:
https://github.com/grpc/grpc-go/commit/596a6acc87c73c3bc398a60ef0089976491ca060
https://github.com/grpc/grpc-go/pull/1392

**Comment by mwitkow** [comment]
This is now fixed
