### ISSUE TITLE
grpc_retry: Why does the serverStreamingRetryingStream never empty its buffer?

### ISSUE THREAD

**Issue by jhedev** [grpc-ecosystem/go-grpc-middleware#88]
I was wondering why the `serverStreamingRetryingStream` does not empty its buffer `bufferedSends` after these have successfully been sent when the stream is reestablished?

**Comment by mwitkow** [comment]
For example, let's say you're sending a client stream, and the first message successfully was written by the client to the TCP stream (and thus "sent") but never got to the server (e.g. connection torn down). You want to be able to resend that.

Please reopen if there's a use case that this approach prohibits.
