### ISSUE TITLE
Add ability to skip logging/change level of certain method calls (e.g.  healthcheck)

### ISSUE THREAD

**Issue by sstarcher** [grpc-ecosystem/go-grpc-middleware#89]
What's the best way to suppress certain response output.  In this case we have health checks that are called every so often which we don't really want to fill up the logs.  Is the best solution to wrap the grpc_logrus.UnaryServerInterceptor handler with my own handler to filter out the calls.

**Comment by mwitkow** [comment]
Interesting, I think that would be a great feature request.

I'd add an `Option` to the logging middlewares (zap and logrus) that allows you to have `func(methodName string, ctx context) level` that can skip the logging, or maybe better: override the log level?

@sstarcher happy to accept a PR :)

**Comment by domgreen** [comment]
@mwitkow i think we can close this we now have a decider that will allow @sstarcher to do exactly this in #113 ... so if a successful health check call comes in we can decide not to log.

**Comment by sstarcher** [comment]
@domgreen perfect thanks
