### ISSUE TITLE
grpc_logrus SystemField

### ISSUE THREAD

**Issue by mrbanzai** [grpc-ecosystem/go-grpc-middleware#94]
I'm confused what `SystemField` is intended to represent, as it seems that it's being used as both a key (https://github.com/grpc-ecosystem/go-grpc-middleware/blob/82921fcf811d228d2fa202bc31238b356bf9f8d5/logging/logrus/client_interceptors.go#L60) and a value (https://github.com/grpc-ecosystem/go-grpc-middleware/blob/82921fcf811d228d2fa202bc31238b356bf9f8d5/logging/logrus/grpclogger.go#L14).

My assumption would be that it would represent the value of the "system" field in the log message.  Could I get some clarification here?  I'll happily submit a pull request to correct it, if this is indeed an oversight.  Thanks!

**Comment by yifanzz** [comment]
@mrbanzai nice catch. I think we meant to use`SystemField` to represent the field name, not the value. `grpclogger.go` should be corrected. I would be happy to review the your PR.
