### ISSUE TITLE
[Question] Is it possible to select which endpoints to apply MW to?

### ISSUE THREAD

**Issue by deltaskelta** [grpc-ecosystem/go-grpc-middleware#96]
If I only wanted to run the auth middleware on auth protected endpoints, can this be accomplished?

**Comment by dietb** [comment]
Something sort of like this will work.

```
func (s *server) AuthFuncOverride(ctx context.Context, fullMethodName string) (context.Context, error) {
    // This is will bypass on anything not matching "/package.Object/GetterName"
    if fullMethodName != "/package.Object/GetterName" {
        return ctx, nil
    }
}
```

**Comment by deltaskelta** [comment]
@dietb thanks. I was kind of thinking it had to be like this. Is `GetterName` the name of the endpoint as defined in the proto file?

**Comment by dietb** [comment]
Correct.  If there's any confusion, you can do a println of fullMethodName before any processing.
